### ISSUE TITLE
SM like SK should be AI service agnostic

### ISSUE THREAD

**Issue by geffzhang** [microsoft/kernel-memory#101]
Semantic Kernel  1.0 is AI service agnostic.   Semantic kernel now only support  azure openai/openai , We  should  make the Semantic memory  AI provider agnostic.

**Comment by dluc** [comment]
hi @geffzhang I think memory is already provider agnostic, isn't it? SearchClient depends on `ITextEmbeddingGeneration` and `ITextGeneration` so you should be able to leverage any custom class implementing those interfaces, talking to any LLM

**Comment by geffzhang** [comment]
thanks, I see repo only support openai/azure openai，I tried to support [llamasharp](https://github.com/SciSharp/LLamaSharp) these two days and it is indeed service agnostic

**Comment by xbotter** [comment]
> hi @geffzhang I think the solution is already provider agnostic, isn't it? SearchClient depends on `ITextEmbeddingGeneration` and `ITextGeneration` so you should be able to leverage any custom class implementing those interfaces, talking to any LLM

Can we extract the ITextEmbeddingGeneration and ITextGeneration interfaces into a separate Nuget package so that AI providers can implement them on their own?

**Comment by dluc** [comment]
@geffzhang the integration with llamasharp should look something like this:

```
using Microsoft.SemanticMemory;
using Microsoft.SemanticMemory.AI;
using Microsoft.SemanticMemory.MemoryStorage.Qdrant;

public class Program
{
    public static void Main()
    {
        var llamaConfig = new LlamaConfig
        {
            // ...
        };

        var openAIConfig = new OpenAIConfig
        {
            EmbeddingModel = "text-embedding-ada-002",
            APIKey = Env.Var("OPENAI_API_KEY")
        };

        var memory = new MemoryClientBuilder()
            .WithCustomTextGeneration(new LlamaTextGeneration(llamaConfig))
            .WithOpenAITextEmbedding(openAIConfig)
            .WithQdrant(new QdrantConfig { /* ... */ });

        // ...
    }
}

public class LlamaConfig
{
    // ...
}

public class LlamaTextGeneration : ITextGeneration
{
    private readonly LlamaConfig _config;

    public LlamaTextGeneration(LlamaConfig config)
    {
        this._config = config;
    }

    public IAsyncEnumerable<string> GenerateTextAsync(
        string prompt,
        TextGenerationOptions options,
        CancellationToken cancellationToken = new())
    {
        // ...
    }
}

```

The vector size is handled automatically, as long as it is consistent across executions.

The code above is using:

```
    <PackageReference Include="LLamaSharp" Version="0.5.1"/>
    <PackageReference Include="Microsoft.SemanticMemory.Core" Version="0.3.231009.6-preview"/>
```

@xbotter it should be possible to use custom logic with the existing nuget.

**Comment by AsakusaRinne** [comment]
Thanks to the great work from @xbotter, LLamaSharp is about to have an integration for kernel-memory. I'll appreciate it if someone of KM developers could help to review [this PR](https://github.com/SciSharp/LLamaSharp/pull/226).

**Comment by dluc** [comment]
@xbotter 
> Can we extract the ITextEmbeddingGeneration and ITextGeneration interfaces into a separate Nuget package so that AI providers can implement them on their own?

done 👍 see v0.18 / PR #189
