### ISSUE TITLE
IContentStorage Delete methods fail when DocumentId contains invalid char

### ISSUE THREAD

**Issue by luismanez** [microsoft/kernel-memory#108]
The different ```ImportDocument``` methods work with a ```Document``` class. That class, when setting the DocumentId, is doing some replacements to avoid special chars:

```csharp
public string Id
    {
        get { return this._id; }
        set
        {
            this._id = string.IsNullOrWhiteSpace(value)
                ? FsNameToId(RandomId())
                : FsNameToId(value);
        }
    }
```

Basically, applies this regular expression: 

```csharp
private static readonly Regex s_replaceSymbolsRegex = new(@"[\s|\||\\|/|\0|'|\`|""|:|;|,|~|!|?|*|+|\-|=|_|^|@|#|$|%|&]");
```

So, if your documentId is _"hello-world"_, it changes to _"hello_world"_, so all the temp files are created within _"hello_world"_ folder.

However, that regular expression is not applied when the _DocumentId_ is passed as string to the different _Delete_ methods in the ```IContentStorage``` implementations. So, if you try to delete the document, the Temp folder is not deleted, as it tries to delete _"hello-world"_ folder, which does not exist, as it was created as "hello_world" folder. Even worse, as you end up with 2 different folders: _Hello-world_ (created by the Delete handler leaving just the _pipeline_status.json_) and _Hello_world_ folder, created by the extraction handler.

I think the easiest solution is, in the SimpleFileStorage class:

```csharp
    private string GetDocumentPath(string index, string documentId)
    {
        return Path.Join(this.GetIndexPath(index), Document.FsNameToId(documentId));
    }
```

And in the AzureBlobStorage class:

```csharp
    private static string JoinPaths(string index, string documentId)
    {
        return $"{index}/{Document.FsNameToId(documentId)}";
    }
```

However, not sure if we shouldn´t refactor these classes to pass directly a Document object...

Happy to do a PR if my approach sounds good @dluc 

Thanks!

**Comment by dluc** [comment]
@luismanez does this happen also with the latest code in `main` branch?

**Comment by luismanez** [comment]
Wow!... you fixed the issue at the same time I opened it 😄 

It's working fine as now the "-" is a supported character. I also see that an Exception is thrown if the document ID has any of the invalid chars defined in a regex. Sounds good to me (guess should be documented somewhere).

Thanks a lot!
