### ISSUE TITLE
Is it possible to make Microsoft.SemanticMemory.Core depends on .Standard instead of .net 6?

### ISSUE THREAD

**Issue by dawwa** [microsoft/kernel-memory#119]
We're trying to use the lib in a component built with .net standard 2.0.
It will be good to have this Microsoft.SemanticMemory.Core support being used in a .net standard project instead of requiring .net 6.

https://www.nuget.org/packages/Microsoft.SemanticMemory.Core/0.4.231023.1-preview

**Comment by dluc** [comment]
hi @dawwa for your scenario we highly recommend using only the `Client` nuget which is built for .NET Standard 2.0, deploying the memory as a service, separately. Moving the Core nuget to .NET Standard 2.0 would require a lot of changes and workarounds, and we would be stuck forever on an old version, making it hard to use new features coming to .NET.

**Comment by dluc** [comment]
As the matter at hand appears to be resolved, I'll be closing this issue for now. However, please don't hesitate to reach out if you have any further questions or concerns. We're more than happy to reopen the issue or continue the conversation as needed 😊
