### ISSUE TITLE
Service: ImportDocumentAsync Error - The document ID contains invalid symbols (Parameter 'id')

### ISSUE THREAD

**Issue by jickler-o** [microsoft/kernel-memory#120]
When running Kernel Memory as a service and trying to import a document we are getting this error: The document ID contains invalid symbols (Parameter 'id').

To clarify we are hashing file names before assigning them as the id to make sure that documents that may have the same name but are different are still separated. Below is the string that threw the error pulled from VS debugger as well as the relevant code:

Document Id = "487BC53B60CFBD42167A0488A78347929E0FE811FC705A94253E419CA5911360"
FileName Tested: Apple Inc. v. Pepper.pdf
Where Nom is of type [MemoryWebClient](https://github.com/microsoft/kernel-memory/blob/0db634b9868806b91a705bddcf875e6107f0e441/dotnet/ClientLib/MemoryWebClient.cs#L4).

```C#
public async Task UploadFile(InputFileChangeEventArgs e)
{
    SetIsBusy(true, "Uploading...");

    string hashedFileName = BitConverter.ToString(System.Security.Cryptography.SHA256.Create().ComputeHash(System.Text.Encoding.UTF8.GetBytes(e.File.Name))).Replace("-", "");

    using MemoryStream memoryStream = new();
    using Stream fileStream = e.File.OpenReadStream(maxAllowedSize: 20 * 1024 * 1024);
    await fileStream.CopyToAsync(memoryStream);
    memoryStream.Seek(0, SeekOrigin.Begin);
    try
    {
        await DocumentIngestor.Nom!.ImportDocumentAsync(
            content: memoryStream,
            documentId: hashedFileName,
            fileName: e.File.Name,
            steps: PipelineWithoutSummary,
            tags: new() { { "user", UserModel.Email } });

        await DocumentIngestor.AddSnack(hashedFileName);

        SetIsBusy(false);
    }
    catch (Exception excep)
    {
        Console.WriteLine(excep.Message);
        SetIsBusy(false);
    }
}
```
I am not sure if this is a bug or if our ID does have some invalid characters, although they all seem to be standard. If anyone can help us resolve this issue it would be appreciated!

**Comment by jickler-o** [comment]
I have been digging into the reason for this and saw that the Document class has a Regex expression to test the ID. I also saw the `ReplaceInvalidChars()` method. I have implemented that method in the below code, but it still does not resolve the error, even though any invalid characters should be replaced.

```C#
public async Task UploadFile(InputFileChangeEventArgs e)
{
    SetIsBusy(true, "Uploading...");

    string hashedFileName = Document.ReplaceInvalidChars(BitConverter.ToString(System.Security.Cryptography.SHA256.Create().ComputeHash(System.Text.Encoding.UTF8.GetBytes(e.File.Name))).Replace("-", ""));

    using MemoryStream memoryStream = new();
    using Stream fileStream = e.File.OpenReadStream(maxAllowedSize: 20 * 1024 * 1024);
    await fileStream.CopyToAsync(memoryStream);
    memoryStream.Seek(0, SeekOrigin.Begin);
    try
    {
        await DocumentIngestor.Nom!.ImportDocumentAsync(
            content: memoryStream,
            documentId: hashedFileName,
            fileName: e.File.Name,
            steps: PipelineWithoutSummary,
            tags: new() { { "user", UserModel.Email } });

        await DocumentIngestor.AddSnack(hashedFileName);

        SetIsBusy(false);
    }
    catch (Exception excep)
    {
        Console.WriteLine(excep.Message);
        SetIsBusy(false);
    }
}
```

**Comment by jickler-o** [comment]
Another interesting twist with this issue is that the Regex doesn't seem to actually match. See the output and modified code below:
### Modified Code
```C#
public async Task UploadFile(InputFileChangeEventArgs e)
{
    SetIsBusy(true, "Uploading...");

    string hashedFileName = Document.ReplaceInvalidChars(BitConverter.ToString(System.Security.Cryptography.SHA256.Create().ComputeHash(System.Text.Encoding.UTF8.GetBytes(e.File.Name))).Replace("-", ""));
    Regex s_replaceSymbolsRegex = new(@"[\s|\||\\|/|\0|'|\`|""|:|;|,|~|!|?|*|+|=|^|@|#|$|%|&]");

    using MemoryStream memoryStream = new();
    using Stream fileStream = e.File.OpenReadStream(maxAllowedSize: 20 * 1024 * 1024);
    await fileStream.CopyToAsync(memoryStream);
    memoryStream.Seek(0, SeekOrigin.Begin);
    Console.WriteLine($"Hashed File Name: {hashedFileName}");
    Console.WriteLine($"Matches Regex: {s_replaceSymbolsRegex.IsMatch(hashedFileName).ToString()}");
    try
    {
        await DocumentIngestor.Nom!.ImportDocumentAsync(
            content: memoryStream,
            documentId: hashedFileName,
            fileName: e.File.Name,
            steps: PipelineWithoutSummary,
            tags: new() { { "user", UserModel.Email } });

        await DocumentIngestor.AddSnack(hashedFileName);

        SetIsBusy(false);
    }
    catch (Exception excep)
    {
        Console.WriteLine(excep.Message);
        SetIsBusy(false);
    }
}
```
### Output
Hashed File Name: 487BC53B60CFBD42167A0488A78347929E0FE811FC705A94253E419CA5911360
Matches Regex: False
The document ID contains invalid symbols (Parameter 'id')

### Further Explanation
the regex in the above code is pulled directly from the definition of the Document class. As you can see, we try to sanitize the doc ID and then we also check if the Regex matches the sanitized ID. The Regex match here returns false, but the Kernel Memory service still throws an error.

**Comment by dluc** [comment]
there might be a bug in the regex, catching `0` (ASCII 48) rather than `NUL` (ASCII 0). I'm planning to replace the regex to the opposite logic. Rather than checking if the ID contains invalid chars, checking if the ID contains only valid chars, I think that will fix the problem

**Comment by dluc** [comment]
There's a bug in `FileCollection`: when using streams, the filename is validated as if it was a document ID. That's old logic that should have been removed.

```csharp
public void AddStream(string? fileName, Stream content)
    {
        if (content == null)
        {
            throw new KernelMemoryException("The content stream is NULL");
        }

        fileName = Document.ValidateId(fileName); // <======
        
        // ...
    }
```

**Comment by dluc** [comment]
Should be fixed in version **0.5.231028.3-preview**.

**Comment by jickler-o** [comment]
Thank you for getting to this so quickly! I will await that version's publishing soon!

**Comment by dluc** [comment]
[the version is out](https://www.nuget.org/packages/Microsoft.KernelMemory.Core/)
