### ISSUE TITLE
KernelMemoryBuilder ：how to change  open-ai net-proxy  in china

### ISSUE THREAD

**Issue by kill136** [microsoft/kernel-memory#122]
var memory = new KernelMemoryBuilder()
    .WithOpenAIDefaults("sk-")
    //.FromAppSettings() //=> read "KernelMemory" settings from appsettings.json (if available), see https://github.com/microsoft/kernel-memory/blob/main/dotnet/Service/appsettings.json as an example
    // .WithAzureBlobsStorage(new AzureBlobsConfig {...})                                              => use Azure Blobs
    // .WithAzureCognitiveSearch(Env.Var("ACS_ENDPOINT"), Env.Var("ACS_API_KEY"))                      => use Azure Cognitive Search
    // .WithQdrant("http://127.0.0.1:6333")                                                            => use Qdrant docker
    // .WithAzureFormRecognizer(Env.Var("AZURE_COG_SVCS_ENDPOINT"), Env.Var("AZURE_COG_SVCS_API_KEY")) => use Azure Form Recognizer OCR
   
    .BuildServerlessClient();

**Comment by dluc** [comment]
hi @kill136, you mean how to change the internal value "https://api.openai.com" to a different URL?

**Comment by galamshar** [comment]
Up! I wanna try to specify a http proxy for all the traffic. Any solutions here?

**Comment by dluc** [comment]
I would start from here https://github.com/Azure/azure-sdk-for-net/issues/37794 see last message

**Comment by dluc** [comment]
I'm going to mark this issue as closed but we're just one comment away if you need further help!

**Comment by qihangnet** [comment]
#228 After merging this PR, it can also easily resolve this issue.
