### ISSUE TITLE
kernel-memory in relationship with semantic-kernal

### ISSUE THREAD

**Issue by liammoat** [microsoft/kernel-memory#128]
I would like to better understand the relationship between [kernel-memory](https://github.com/microsoft/kernel-memory) and [semantic-kernal](https://github.com/microsoft/semantic-kernel).

I understand this project targets the specific requirement of "talk to my data" and, from my exploration, provides greater functionality compared to SK's Memory skills. It also works great as a standalone project, with capabilities to index, query, and provide natural language summarisation etc.

The README says:

> Designed for seamless integration as a Plugin with [Semantic Kernel](https://github.com/microsoft/semantic-kernel)

However, I cannot see how this is intended to work from an implementation perspective. All the samples use kernel-memory directly, without the need for SK. Are there any samples for this scenario?

**Comment by lanyeeee** [comment]
For the sake of understanding
let's say you're using Qdrant as a backend
import a pdf about the use of nginx
and then ask what nginx is, it works like this:

When you import file:
**pdf file after tokenize, will be split into multiple partition**
each partition will be sent to the LLM for embedding
**and then each partition data with its corresponding embedding data will be saved into the Qdrant**

When you ask:
your question will be sent to LLM for embedding
**the embedding data of the question will be used to query in Qdrant to find out the partitions related to the question**
**and then the partitions will be written as facts in the prompt**
like this
```
Facts:
{{$facts}}
======
Given only the facts above, provide a comprehensive/detailed answer.
You don't know where the knowledge comes from, just answer.
If you don't have sufficient information, reply with 'INFO NOT FOUND'.
Question: {{$input}}
Answer: 
```
and finally the prompt will be sent to LLM to get the answer.

The bold parts are done by kernel-memory, other parts are done by Semantic Kernel

**Comment by crickman** [comment]
Thank you for this question.

Chat-Copilot (https://github.com/microsoft/chat-copilot) is an example of an aplication that utilizes kernel-memory in conjunction with semantic-kernel.

For advanced application case, you may have the need to talk your data along with other prompt, planner, plug-in, or agent based activities.

**Comment by dluc** [comment]
hi @liammoat I suggest looking at Kernel Memory as a Plugin that can be used with Semantic Kernel and SK planners. SK includes a very basic Memory plugin that needs to be maintained in 3 languages and misses some important features like importing files, automatic chunking, RAG, asynchronous data ingestion, etc.


The plugin for C# is almost ready, see here, there's also one example: https://github.com/microsoft/kernel-memory/pull/146

```csharp

// ...

var memory = new MemoryWebClient("http://127.0.0.1:9001/");

await memory.ImportDocumentAsync("mydocs-NASA-news.pdf");

kernel.ImportFunctions(new MemoryPlugin(memory), "memory");

var skPrompt = """
Question to Kernel Memory: {{$input}}

Kernel Memory Answer: {{memory.ask $input}}

If the answer is empty say 'I don't know' otherwise reply with a preview of the answer, truncated to 15 words.
""";

var oracle = kernel.CreateSemanticFunction(skPrompt);

KernelResult answer = await kernel.RunAsync("any news about Orion?", oracle);

// Answer: Yes, NASA has invited media to see the new test version of the Orion spacecraft...

answer = await kernel.RunAsync("any news about Hubble telescope?", oracle);

// Answer: I don't know.
```

**Comment by liammoat** [comment]
Thanks @dluc - that is exactly what I was looking for. 😊
