### ISSUE TITLE
why is valuekind being returned in payload?

### ISSUE THREAD

**Issue by nicober1** [microsoft/kernel-memory#130]
why is valuekind being returned in payload?

var payload = new Dictionary<string, object> { { "what", "what1" } };
var record = new MemoryRecord
{
    Id = "1",
    Vector = new Embedding { Data = vector },
    Tags = tagCollection,
    Payload = payload
};

await memoryStorage.UpsertAsync("testIndex", record);

var similarVectors = memoryStorage.GetSimilarListAsync("testIndex", new Embedding { Data = vector }, 1);
var list = memoryStorage.GetListAsync("testIndex");

Response:
[
  {
    "id": "1",
    "vector": {
      "data": {
        "length": 0,
        "isEmpty": true
      },
      "length": 0
    },
    "tags": {
      "AnotherKey": [
        "SomeValue"
      ],
      "YetAnotherKey": [
        "Value1",
        "Value2",
        "Value3"
      ]
    },
    "payload": {
      "Url": {
        "valueKind": 2
      }
    }
  }
]

**Comment by dluc** [comment]
hi @nicober1, looks like you're looking at internal implementation details such as classes implementing `IVectorDb`.  I would suggest not to rely or build on that, but to work only with `IKernelMemory`.

**Comment by dluc** [comment]
I think the question has been addressed, otherwise if you come across any more issues or have additional questions, feel free to reopen this issue.
