### ISSUE TITLE
Provide a way to specify task-aware embeddings

### ISSUE THREAD

**Issue by joc-proxem** [microsoft/kernel-memory#132]
Several approaches like https://arxiv.org/pdf/2204.07120.pdf or https://arxiv.org/pdf/2212.09741.pdf distinguish between different kinds of embeddings, e.g. document embeddings vs query embeddings. Adding an optional string parameter to IEmbeddingGeneration.GenerateEmbeddingAsync() could give a way to generate task-aware embeddings.

**Comment by dluc** [comment]
hi @joc-proxem the current implementation follows OpenAI simplification approach. OpenAI model used to distinguish between text and queries but about a year ago they simplified their API: see https://openai.com/blog/new-and-improved-embedding-model. That said, if there are models that perform better, I think we should start comparing the results. Also, are these models ready to consume from .NET?

**Comment by dluc** [comment]
I think like the question has been addressed. If you come across any more issues or have additional questions, feel free to reopen this issue.
