### ISSUE TITLE
Support netstandard2.0

### ISSUE THREAD

**Issue by AsakusaRinne** [microsoft/kernel-memory#136]
I found `Microsoft.KernelMemory.Core 0.5.231030.1-preview` support only net6.0. I'm okay if this is a discussed final decision. However there're still many users with .NET framework, unity and other scenarios without dotnet core runtime. 

I think adding this runtime will attract more users.

**Comment by anthonypuppo** [comment]
Related to #119.

**Comment by AsakusaRinne** [comment]
It's a bit depressing, but okay. Thank you for the reply, closed this as completed.
