### ISSUE TITLE
[QUESTION] Reload an existing index

### ISSUE THREAD

**Issue by DrEight** [microsoft/kernel-memory#150]
I know that this is a silly question, but I've just started to use the KM and I still didn't figure out. 
If I create an index on a memory source, let's say a blob storage, how can load an existing index in memory, without re-uploading the document/text, the second time I re-run the application?

**Comment by dlucr** [comment]
By default KM stores the data in RAM, so everything is lost after the application ends. To import data only once and persist across executions, you'll need to select a storage for files and vectors.

For storage: the solution support Disk and Azure Blobs.
For vectors: the solution support Disk (only for tests), Qdrant, and Azure Cognitive Search.

You can also develop custom storage adapter, everything is based on interfaces.

**Comment by dluc** [comment]
It looks like the question has been addressed. If you come across any more issues or have additional questions, feel free to reopen this issue.
