### ISSUE TITLE
#bug Language support

### ISSUE THREAD

**Issue by DrEight** [microsoft/kernel-memory#151]
I started my test with the nuget package ver.: 0.5.231105.1 and if the question was in italian, the answer was provided in italian. Which it makes sense to me.
Then I updated the nuget package to the latest available version ( actually is 0.8.231109.1 ) and all the answers are now only in english. So if I ask in Italian I receive the answer in english, which it doesn't seems the right behavior to me.

**Comment by dlucr** [comment]
hi @DrEight which LLM are you using?

**Comment by DrEight** [comment]
I'm using gpt-35-turbo-16k

**Comment by dluc** [comment]
That's very strange, I would suggest tweaking the prompt, e.g. adding something similar to "_answer using the same language of the question_".


Once we merge https://github.com/microsoft/kernel-memory/pull/155 changing the prompt will be super easy, see this example: https://github.com/microsoft/kernel-memory/blob/6c34774cc0522abdb23c35dbc086a671cd9778e3/examples/011-dotnet-custom-Prompts/Program.cs

**Comment by dluc** [comment]
#155 has been merged and I would suggest to experiment with the prompt.

If you come across any more issues or have additional questions, feel free to reopen this issue.
