### ISSUE TITLE
nuget ：Conflict with him（semantic kernel 1.0.0 bata6）

### ISSUE THREAD

**Issue by KiisMyGun** [microsoft/kernel-memory#152]
![image](https://github.com/microsoft/kernel-memory/assets/29726759/8736670a-6b7e-422c-8009-c8ec275e1120)

Error：System.TypeLoadException:“Could not load type 'Microsoft.SemanticKernel.Connectors.AI.OpenAI.TextEmbedding.AzureTextEmbeddingGeneration' from assembly 'Microsoft.SemanticKernel.Connectors.AI.OpenAI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3'.”

semantic kernel 1.0.0 bata6： AzureTextEmbeddingGeneration()  ==>  AzureOpenAITextEmbeddingGeneration

**Comment by geffzhang** [comment]
Replace Microsoft.SemanticMemory.* with Microsoft.KernelMomory.*

**Comment by SantanaEduardo** [comment]
I'm getting the same error, @KiisMyGun  were you able to fix it?

**Comment by SantanaEduardo** [comment]
> Replace Microsoft.SemanticMemory.* with Microsoft.KernelMomory.*

Even after this change, it is still failing.

**Comment by anthonypuppo** [comment]
Semantic Kernel `1.0.0-beta6` introduced breaking changes (in this case microsoft/semantic-kernel#3399). Kernel Memory currently depends on `1.0.0-beta5`. You'll need to downgrade Semantic Kernel until the regressions are fixed.

**Comment by dlucr** [comment]
Using KM service should solve the problem, isolating the memory solution from the kernel, as two separate applications. We'll upgrade KM but going with the service is always recommended.

**Comment by SantanaEduardo** [comment]
> Using KM service should solve the problem, isolating the memory solution from the kernel, as two separate applications. We'll upgrade KM but going with the service is always recommended.

I am still getting same error. How should I proceed?

**Comment by KiisMyGun** [comment]
> > Using KM service should solve the problem, isolating the memory solution from the kernel, as two separate applications. We'll upgrade KM but going with the service is always recommended.
> 
> I am still getting same error. How should I proceed?

downgrade Semantic Kernel version (semantic kernel 1.0.0 bata6  =>  semantic kernel 1.0.0 bata5  )

**Comment by dlucr** [comment]
We release a new nuget based on SK beta-6, if that doesn't work perhaps the problem is somewhere else. Could you provide more info, e.g. the versions of all the packages, or maybe a quick repro with an empty project?

**Comment by SantanaEduardo** [comment]
The issue has been resolved after upgrading to beta8.
