### ISSUE TITLE
NuGet package compatibility issues with Azure Functions

### ISSUE THREAD

**Issue by Gpadh** [microsoft/kernel-memory#154]
I'm currently trying to create an Azure function which ingests a document into a Kernel Memory service hosted on Azure. However, when I deploy the function to Azure, it fails to trigger and leaves no log/error messages. I narrowed this problem down to being an incompatibility between the NuGet package and Azure functions. This is because just by adding the NuGet package to the project, the function fails to trigger. Currently, I have a very basic function which is not triggering:
![image](https://github.com/microsoft/kernel-memory/assets/55559061/02f84925-8bcd-4e2e-b956-08794ec002b9)

No Kernel Memory code has been added to this project, all I have done is install the NuGet package.
Is there any workaround for this?

**Comment by dluc** [comment]
@Gpadh would you be able to provide the code to repro? e.g. create a new github repo with all the code?

**Comment by Gpadh** [comment]
@dluc I have provided a repository with the code here, please let me know if there's anything else I can do on my end👍  : https://github.com/Gpadh/Kernel-Memory-Azure-Function-Implementation/tree/master

**Comment by Gpadh** [comment]
I also found this log from application insights, hope this helps: 
![image](https://github.com/microsoft/kernel-memory/assets/55559061/4f65633c-1ec0-4bc4-8530-73b1f7482c14)

**Comment by Gpadh** [comment]
I tried only using the client package, however I get this issue:
![image](https://github.com/microsoft/kernel-memory/assets/55559061/debd26e2-36c5-4b75-9537-d1d504aa7fdf)

I updated the repo so it's only using the client package now

**Comment by dluc** [comment]
thanks for sharing the code, I can see the error about `System.Memory.Data`

**Comment by dluc** [comment]
looks like the Azure Function SDK includes `System.Memory.Data 8.0.0` while KM ClientLib is looking for version `7.0.0`

**Comment by dluc** [comment]
The problem seems to be with Azure Functions runtime removing from the app what it believes are redundant assemblies (to save space and to increase perf), in this case KM dependencies. Moving to the newer AF version with isolated worker model should fix the problem.

However, this quick change fixed the problem on my tests:

```diff
--- a/lexingest2.csproj
+++ b/lexingest2.csproj
@@ -1,14 +1,15 @@
 <Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
     <TargetFramework>net6.0</TargetFramework>
     <AzureFunctionsVersion>v4</AzureFunctionsVersion>
+    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
   </PropertyGroup>
   <ItemGroup>
     <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.1" />
     <PackageReference Include="Microsoft.KernelMemory.Client" Version="0.9.231114.1-preview+dd6c4ac" />
     <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.2.0" />
     <PackageReference Include="System.Memory.Data" Version="8.0.0" />
     <PackageReference Include="System.Text.Json" Version="8.0.0" />
   </ItemGroup>
   <ItemGroup>
     <None Update="host.json">
```

**Comment by dluc** [comment]
It looks like the problem has been resolved. If you come across any more issues or have additional questions, feel free to reopen this issue.

**Comment by Gpadh** [comment]
@dluc 
Hi Devis, thanks for the help.

I had a quick question about the file ingestion limit for the MemoryWebClient. I'm currently trying to import a ~125GB file into Kernel memory, but it fails with the following error:
![image](https://github.com/microsoft/kernel-memory/assets/55559061/d20a1896-ddc9-435f-bc29-37e3d14b6ccc)

I'm pretty sure this is related to file size. Is there a maximum byte limit for documents that can be uploaded to Kernel Memory? Furthermore, is there a way to configure a limit for this?

**Comment by Gpadh** [comment]
Also I don't think I have the permissions to reopen issues, should I make a new one?

**Comment by dluc** [comment]
@Gpadh since it's a different question/problem I would open a separate issue. 125GB seems a very big doc, could you provide more info?
