### ISSUE TITLE
WithQdrant doesn't allow specifying the collection

### ISSUE THREAD

**Issue by JohnGalt1717** [microsoft/kernel-memory#162]
... and I can't figure out any other way to specify which collection should be used.

Is there a way to specify this? Can this be opened up to include the collection?

**Comment by dluc** [comment]
hi @JohnGalt1717 you can specify the collection using the `index` parameter in the memory API

**Comment by JohnGalt1717** [comment]
Can you elaborate? I don't see an Index property or method or parameter anywhere on Memory in C#.

**Comment by dluc** [comment]
please see https://github.com/microsoft/kernel-memory/blob/main/service/Core/MemoryStorage/Qdrant/QdrantMemory.cs which implements `IMemoryDb` interface. All methods accept an `index` string parameter, that internally maps to qdrant collection name.

**Comment by dluc** [comment]
similarly `IKernelMemory` methods accept the same `index` param
