### ISSUE TITLE
Cyrillic encoding problem

### ISSUE THREAD

**Issue by galamshar** [microsoft/kernel-memory#168]
When uploading a document containing Cyrillic alphabet in a vector database, the text is encoded in unicode. Has anyone encountered such a problem and is there a solution to the problem? Why is this happening? I will be glad of any help!
![image](https://github.com/microsoft/kernel-memory/assets/58138603/51c53dbc-1007-43f8-9622-a8336ca4f587)

**Comment by duvsha-nit** [comment]
Hello @galamshar,

Have you made any progress in addressing this issue? It appears that kernel memory behaves consistently when using non-Latin languages.

Your insights and updates on this matter would be greatly appreciated.

Thank you
