### ISSUE TITLE
AskAsync .NET incompatibility with Azure.AI.OpenAI 1.0.0-beta.10

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/kernel-memory#190]
Trying to use `IKernelMemory.AskAsync` with Azure.AI.OpenAI 1.0.0-beta.10: 

```xml
<PackageReference Include="Azure.AI.OpenAI" Version="1.0.0-beta.10" />
```

Results in errors like this:

```
[BE]       System.MissingMethodException: Method not found: 'System.Collections.Generic.IList`1<Azure.AI.OpenAI.ChatMessage> Azure.AI.OpenAI.ChatCompletionsOptions.get_Messages()'.
[BE]          at Microsoft.KernelMemory.AI.AzureOpenAI.AzureTextGeneration.GenerateTextAsync(String prompt, TextGenerationOptions options, CancellationToken cancellationToken)+MoveNext()
[BE]          at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
[BE]          at Microsoft.KernelMemory.AI.AzureOpenAI.AzureTextGeneration.GenerateTextAsync(String prompt, TextGenerationOptions options, CancellationToken cancellationToken)+System.IAsyncDisposable.DisposeAsync()
[BE]          at Microsoft.KernelMemory.Search.SearchClient.AskAsync(String index, String question, ICollection`1 filters, Double minRelevance, CancellationToken cancellationToken)
```

**Comment by dluc** [comment]
@johnnyreilly could you upgrade to 1.0.0-beta.9? 

KM inherits the package from SK, which is currently using beta9, see https://github.com/microsoft/semantic-kernel/blob/main/dotnet/Directory.Packages.props

**Comment by dluc** [comment]
oops, just realized it would be a downgrade. I opened an issue on SK repo: https://github.com/microsoft/semantic-kernel/issues/4094

**Comment by johnnyreilly** [comment]
Similar issue with `1.0.0-beta.11` by the looks

**Comment by dluc** [comment]
KM updated, SK v1, using OpenAI 1.0.0-beta.12.  Since KM inherits the library from SK, it's probably faster reporting these issued on SK repo at https://github.com/microsoft/semantic-kernel/issues
