### ISSUE TITLE
Integrating with rc-4 of SemanticKernel leads to ambiguous invocation errors when calling AddOpenAIChatCompletion and AddOpenAITextEmbeddingGeneration

### ISSUE THREAD

**Issue by glorious-beard** [microsoft/kernel-memory#205]
I think it's because Kernel Memory is referring to the package Microsoft.SemanticMemory.Connectors.AI.OpenAI, which has been deprecated. Most classes in that package have been moved to Microsoft.SemanticMemory.Connectors.OpenAI. This results in both rc-3 and rc-4 versions of the same kernel builder extensions with the same classname in the same namespace.

(See [this line](https://github.com/microsoft/kernel-memory/blob/f6daebddfda87cd56233e750aa1dc3490318f20c/service/Core/Core.csproj#L38)).

**Comment by vkynchev** [comment]
`Microsoft.SemanticKernel.AI.*` namespace doesn't exist in SemanticKernel 1.0.0-rc4. Package reference should be updated  in Microsoft.KernelMemory projects and the errors should be fixed.

<img width="809" alt="Screenshot 2023-12-14 at 13 17 58" src="https://github.com/microsoft/kernel-memory/assets/10143016/ca538509-8067-4a92-aad1-710c899be544">

**Comment by dluc** [comment]
Fixed, please see the last nugets and code, which is based on SK v1.0.1
