### ISSUE TITLE
Ingest using HTML or web link

### ISSUE THREAD

**Issue by ovais-panjwani** [microsoft/kernel-memory#207]
Hi,

I hope you are doing well! I'm trying to ingest documents from our internal wiki, but I have to copy all the contents from the wiki into a txt file, then I can ingest the data as memory. I was wondering if we can add an improvement to be able to ingest documents via html files or web links? Thanks!

**Comment by dluc** [comment]
hi @ovais-panjwani good news, that's part of the memory API :-)

```csharp
await memory.ImportWebPageAsync(
    "https://raw.githubusercontent.com/microsoft/kernel-memory/main/README.md");
```

**Comment by dluc** [comment]
The API above should address the request, otherwise please let us know :-)

**Comment by ovais-panjwani** [comment]
Ah I see, thanks! I think the version we're on didn't have it so we just
need to update it.

Sincerely,
Ovais Panjwani
