### ISSUE TITLE
Home grown Tokenization library vs. Microsoft Tokenizer library

### ISSUE THREAD

**Issue by MaxAkbar** [microsoft/kernel-memory#220]
Hello, just a quick question what is the purpose of using the tokenization that is ported vs. [Microsoft Tokenizer Library](https://github.com/microsoft/Tokenizer/tree/main)? 

Thank you 🙏

**Comment by dluc** [comment]
no particular reason, the library in the repo has been developed sooner (used to be here), it's a direct port of OpenAI lib and has been optimized over the time for performance. Tokenizers can be injected though, so if one prefers using a different implementation that's possible.
