### ISSUE TITLE
Support Running as Serverless but with Data Persistence

### ISSUE THREAD

**Issue by HazyFish** [microsoft/kernel-memory#229]
My use case does not require a Web API layer or queue for data ingestion, but I need data persisted in a database. Currently, if we run it in Serverless mode, everything is volatile. If we run it in service mode, we need all the components which might not be necessary for all use cases. Could we refactor the code to make it more modular and support some middle grounds between the 2?

**Comment by dluc** [comment]
hi @HazyFish the volatile mode is only the default configuration, and you can easily change that. There's 2 components to setup: file storage and memory storage.

Here's a few examples:

```csharp
var memory = new KernelMemoryBuilder()
    .WithOpenAI(openAICfg)
    .WithAzureBlobsStorage(azureBlobsConfig) // file storage in the cloud, for Prod use cases
    .WithAzureAISearch(azureSearchConfig)  // memory storage in the cloud, for Prod use cases
    .Build<MemoryServerless>();
```

```csharp
var memory = new KernelMemoryBuilder()
    .WithOpenAI(openAICfg)
    .WithSimpleFileStorage(new SimpleFileStorageConfig { StorageType = FileSystemTypes.Disk }) // local file storage
    .WithQdrantMemoryDb(qdrantConfig) // memory storage on Qdrant, both local or in the cloud
    .Build<MemoryServerless>();
```

```csharp
var memory = new KernelMemoryBuilder()
    .WithOpenAI(openAICfg)
    .WithSimpleFileStorage(new SimpleFileStorageConfig { StorageType = FileSystemTypes.Disk }) // local file storage
    .WithSimpleVectorDb(new SimpleVectorDbConfig { StorageType = FileSystemTypes.Disk }) // memory storage, designed for tests/dev, doesn't scale to millions of memories
    .Build<MemoryServerless>();
```

There are also other options, e.g. type `.With...` to see IntelliSense suggestions.

**Comment by HazyFish** [comment]
Thank you so much for the prompt response!!! I hope this is added to the README.md for more clarity. Should I close the issue now?

**Comment by dluc** [comment]
@HazyFish I'll close the issue -- we're updating the docs and we'll make this easier to find, thanks for the feedback!

You can take a sneak peak at https://microsoft.github.io/kernel-memory to see the work in progress :-)
