### ISSUE TITLE
[Feature Request] Document - load string content 

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/kernel-memory#254]
### Context / Scenario

Is some cases I do't have acutal file to upload, so I think option to create Document with just text will be good.

### The problem

Upload some realtime data in Memory

### Proposed solution

Add some methods like 
```
Document.FromString(string content);
```

### Importance

nice to have

**Comment by dluc** [comment]
@KSemenenko I think `ImportTextAsync` does what you're looking for:

```csharp
    public Task<string> ImportTextAsync(
        string text,
        string? documentId = null,
        TagCollection? tags = null,
        string? index = null,
        IEnumerable<string>? steps = null,
        CancellationToken cancellationToken = default);
```
