### ISSUE TITLE
[Bug] Import for excel

### ISSUE THREAD

**Issue by xuzeyu91** [microsoft/kernel-memory#265]
### Context / Scenario

When I try to import an Excel file, the. xlsx type prompts: Method not found: 'DocumentFormat.' OpenXml OpenXmlElementList DocumentFormat OpenXml OpenXmlElement.get_ ChildElements()

### What happened?

Support for importing Excel files

### Importance

a fix would make my life easier

### Platform, Language, Versions

C#     <PackageReference Include="Microsoft.KernelMemory.Core" Version="0.26.240116.2" />

### Relevant log output

```shell
Method not found: 'DocumentFormat.OpenXml.OpenXmlElementList DocumentFormat.OpenXml.OpenXmlElement.get_ChildElements()'.
```

**Comment by dluc** [comment]
Looks like an issue with DocumentFormat.OpenXml 3.x

**Comment by dharmendra-patel** [comment]
We are still getting the error

![image](https://github.com/microsoft/kernel-memory/assets/66126383/b4073163-82ec-468e-bf27-bc50a7c3176f)

**Comment by dluc** [comment]
KM uses DocumentFormat.OpenXml 2.20.0, I would suggest not using 3.x.

**Comment by xkzhud** [comment]
> KM uses DocumentFormat.OpenXml 2.20.0, I would suggest not using 3.x.

i got the same problem ，so annoying

**Comment by dharmendra-patel** [comment]
One of our referenced project was using 3.x, updating it to 2.20.0 resolved the error. Thank you Devis.

**Comment by dluc** [comment]
@xuzeyu91 @xkzhud @dharmendra-patel I reported the issue here if you want to upvote the request: https://github.com/ClosedXML/ClosedXML/issues/2315

**Comment by dluc** [comment]
Fixed in https://github.com/microsoft/kernel-memory/pull/792
