### ISSUE TITLE
[Question] MemoryFilter issue

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/kernel-memory#279]
### Context / Scenario

I found a problem with filtering,
I need to search in several files whose id I know

```cs
var filter = new MemoryFilter();

foreach (var file in _files)
{
    if (file.IsReady)
    {
        filter = filter.ByDocument(file.DocumentId);
    }
}
```
but as a result, I don't get any answers.
although when I have one file everything works fine.

but if I will use some like
```cs
var filter = new MemoryFilter().ByTag("tag", "MyFilesTag");
```
then it works

### What happened?

search cannot find the night one when two files are added in the filter

### Importance

a fix would make my life easier

### Platform, Language, Versions

C#

**Comment by KSemenenko** [comment]
```cs
 List<MemoryFilter> filters = new List<MemoryFilter>();
        foreach (var file in _files)
        {
            if(file.IsReady)
                filters.Add(new MemoryFilter().ByDocument(file.DocumentId));
        }
MemoryAnswer answer = await this._memory.AskAsync(
            question: question,
            filters: filters,
            index: AvenirConstants.IndexForSemanticMemory,
            minRelevance: MinRelevance,
            cancellationToken: cancellationToken).ConfigureAwait(false);
```
also not working, No relevace sourses

**Comment by dluc** [comment]
hi @KSemenenko that code works as intended, I don't think it's a bug. Let's say you import two files as two separate documents:

```
File 1 => Doc ID = A
File 2 => Doc ID = B
```

In the initial code, you are using **a single** filter with two conditions, asking for memories extracted from **both** files, and the result is empty. The code is doing:

```csharp
var filter = new MemoryFilter();
filter.ByDocument("A");
filter.ByDocument("B");
```

which results in:

> find memories where docId == "A" **AND** docId == "B"

In your latest snippet of code, you're using **two** filters, which results in:

> find memories where docId == "A" **OR** docId == "B"

**Comment by KSemenenko** [comment]
Now I get it, thanks for explanation 👍
