### ISSUE TITLE
[Feature request] Allow to configure default collection used with Qdrant

### ISSUE THREAD

**Issue by DavidNorena** [microsoft/kernel-memory#285]
### Context / Scenario

Im trying to use the QdrantDb but without using the default collection name

### What happened?

I get this error

warn: Microsoft.KernelMemory.MemoryDb.Qdrant.Client.QdrantClient[0]
      Qdrant responded with error: NotFound, {"status":{"error":"Not found: Collection `default` doesn't exist!"},"time":9.137e-6}
warn: Microsoft.KernelMemory.Search.SearchClient[0]
      No memories available

### Importance

edge case

### Platform, Language, Versions

C# using .net 8 on linux

### Relevant log output

```shell
warn: Microsoft.KernelMemory.MemoryDb.Qdrant.Client.QdrantClient[0]
      Qdrant responded with error: NotFound, {"status":{"error":"Not found: Collection `default` doesn't exist!"},"time":9.137e-6}
warn: Microsoft.KernelMemory.Search.SearchClient[0]
      No memories available
```
```

**Comment by DavidNorena** [comment]
While is not an error the library should allow me to specify the collection name right ?

**Comment by dluc** [comment]
@DavidNorena could you share a snippet of code to show how to reproduce the error?

**Comment by DavidNorena** [comment]
When you init the memory with Qdrant there is no way to change the default collection which I believe is something needs improvement

![image](https://github.com/microsoft/kernel-memory/assets/26279057/2c33a7aa-3cd3-478d-bd94-804b0715ca38)

We were not using the default collection in qdrant, so If you dont specify when searching it will throw the warning ...

![image](https://github.com/microsoft/kernel-memory/assets/26279057/f15984b3-8efd-44fc-8664-e4e8acde40de)

I believe there should be a way to init the default collection on configuration right ?

**Comment by dluc** [comment]
I agree it would be nice configuring more details about Qdrant, like the default collection, a prefix, field names etc, and we'd welcome PRs in that sense. 

With regard to the logs, those are only warnings, and the connector creates the collection automatically when missing.

**Comment by dluc** [comment]
thanks @marcominerva for implementing this! see https://github.com/microsoft/kernel-memory/pull/339
