### ISSUE TITLE
[Feature request] Is there a release date for the FromConfiguration method to come back?

### ISSUE THREAD

**Issue by MaxenceBoucquez** [microsoft/kernel-memory#286]
### Context / Scenario

In my project, I was using the KernelMemoryBuilder.FromConfiguration extension method, but after a package update I can't do it anymore.
I saw the method has been reduced and is now present in the package named "Microsoft.KernelMemory.Service". The thing is I can't find the nuget package for my project so I can't use the method anymore.

### What happened?

You already responded to me that the Service project where the method is is not deployed. I already tried to import only the data I need but it requires to copy all the Service project. 

### Importance

a fix would make my life easier

### Platform, Language, Versions

.net, last Microsoft.KernelMemory.Core version

**Comment by dluc** [comment]
See https://github.com/microsoft/kernel-memory/issues/283
