### ISSUE TITLE
[Bug] [Redis Conector] Redis relevance result is always 0 on 0.27.240205.2

### ISSUE THREAD

**Issue by blinchi** [microsoft/kernel-memory#298]
### Context / Scenario

I'm using Kernel Memory in Serverless mode, in version 0.27.240205.1. When I call the 'SearchAsync' method, it returns the relevance of the search, but in the new version '0.27.240205.2', it always returns 0 for the same search.

### What happened?

In the new version '0.27.240205.2' of the NuGet package 'Microsoft.KernelMemory.MemoryDb.Redis', the relevance of searches is not displayed, always resulting in 0. I have reverted to the previous version of the package.

v.  0.27.240205.1
![image](https://github.com/microsoft/kernel-memory/assets/13270049/357103d3-755e-4bef-b967-51d0572d356e)

v. 0.27.240205.2

![image](https://github.com/microsoft/kernel-memory/assets/13270049/b4b072c9-910c-4c9a-96ed-5866e18e0b25)

### Importance

a fix would make my life easier

### Platform, Language, Versions

C#, in serverless mode.

Microsoft.KernelMemory.Core" Version="0.27.240205.2" 
Microsoft.KernelMemory.MemoryDb.Redis" Version="0.27.240205.1" 
Microsoft.SemanticKernel" Version="1.3.0" 
Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.3.0" 

Procesador	12th Gen Intel(R) Core(TM) i7-1255U   1.70 GHz
RAM instalada	40,0 GB (39,7 GB usable)
Tipo de sistema	Sistema operativo de 64 bits, procesador basado en x64
Lápiz y entrada táctil	La entrada táctil o manuscrita no está disponible para esta pantalla

**Comment by dluc** [comment]
@slorello89 working on it, thanks!
