### ISSUE TITLE
[Bug] Looks like longer responses are cut off

### ISSUE THREAD

**Issue by EelcoKoster** [microsoft/kernel-memory#312]
### Context / Scenario

When I ask a question about a document where I expect a longer answer (like 2.000 characters), the answer is cut off. I tried with different documents and prompts and it looks like the max response is about 300 tokens?

### What happened?

I'm using the MemoryServerless variant in a .Net 7 console app. I imported a PDF document "Building Your Own Product Copilot: Challenges, Opportunities, and Needs" (https://arxiv.org/pdf/2312.14231.pdf). And when I ask the following question "Give me a comprehensive list of all the findings in max 3000 characters". I get an answer that is cut off around 300 tokens?

I'm using Azure OpenAI service met GPT4 model version 1106-Preview and text-embedding-ada-002

Example:
```
            var memory = new KernelMemoryBuilder()
                 .WithAzureOpenAITextGeneration(new AzureOpenAIConfig                                     
                 {
                    APIType = AzureOpenAIConfig.APITypes.ChatCompletion,
                    Auth = AzureOpenAIConfig.AuthTypes.APIKey,
                    APIKey = azureOpenAiKey,
                    Endpoint = azureOpenAiEndpoint,
                    Deployment = azureOpenAiChatDeployment 
                 })
                 .WithAzureOpenAITextEmbeddingGeneration(new AzureOpenAIConfig
                 {
                    APIType = AzureOpenAIConfig.APITypes.EmbeddingGeneration,
                    Auth = AzureOpenAIConfig.AuthTypes.APIKey,
                    APIKey = azureOpenAiKey,
                    Endpoint = azureOpenAiEndpoint,
                    Deployment = azureOpenAiEmbeddingDeployment
                 })
                .Build<MemoryServerless>();

            filename = @"C:\temp\BuildingYourOwnProductCopilot.pdf";
            await memory.ImportDocumentAsync(filename, documentId: "copilot");

            var answer = await memory.AskAsync("Give me a comprehensive list of all the findings in max 3000 characters");
            Console.WriteLine(answer.Result);
```

An example answer is:
"The study on building product copilots, involving 26 professional software engineers, revealed several findings:

1. **Trial and Error Process**: Engineers found prompt engineering to be time-consuming, involving a lot of trial and error in ad-hoc environments.

2. **Prompt Output Wrangling**: Engineers struggled to systematically parse machine-readable outputs from prompts and had to iterate or change approaches frequently.

3. **Context Balance**: Balancing the right amount of context with token limitations was challenging, as was managing and tracking prompt assets.

4. **Advanced Model Behavior**: Engineers faced issues with models getting stuck in loops or going off-track and had difficulty in recognizing task completion.

5. **Testing and Benchmarks**: Traditional software testing methods were inadequate for LLMs, leading to challenges like flaky tests, creating benchmarks, and determining testing adequacy.

6. **Automated Benchmark Creation**: There was interest in systems that convert binary feedback into benchmarks, with a preference for straightforward percentage evaluations and actionable insights.

7. **Metrics and Human Judgment**: There was a disinterest in advanced machine learning metrics, with a focus on software engineering and business-centric metrics, and a belief in the irreplaceable role of human judgment.

8. **Awareness and Visibility**: Tool builders suggested mechanisms for alerting stakeholders of cost changes and recommended rigorous regression testing tools.

9. **Ecosystem Support**: Developers sought a unified "one-stop shop" for tool integration and expressed the need for templates and guidance in tool selection.

10"

It stops at 10... and I expect it to have some text after 10. (I tried this many times and obviously always with different result and it always looks cut off. Ending in the middle of a sentence)

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

I'm using Kernel Memory version 0.28.240212.1 (But also saw this issue with version 0.23.?)

**Comment by marcominerva** [comment]
You can set the maximum number of tokens for the answer when configuring Kernel Memory:

```csharp
var kernelMemory = new KernelMemoryBuilder(builder.Services)
   //...
    .WithSearchClientConfig(new()
    {
        AnswerTokens = 800
    });
```

The default value for this property is 300.

**Comment by EelcoKoster** [comment]
Thank you! I tried some config changes, but was not aware of this one.
And it solves my problem!
