### ISSUE TITLE
[Question] How to submit web pages via Web API

### ISSUE THREAD

**Issue by metropol** [microsoft/kernel-memory#315]
### Context / Scenario

I have KM running as a service. It runs locally with temporary storage. 

dotnet run
***************************************************************************************************************************
* Web service         : Enabled
* Web service auth    : Disabled
* Pipeline handlers   : Enabled
* OpenAPI swagger     : Enabled
* Logging level       : Information
* Memory Db           : Microsoft.KernelMemory.MemoryStorage.DevTools.SimpleVectorDb
* Content storage     : Microsoft.KernelMemory.ContentStorage.DevTools.SimpleFileStorage
* Embedding generation: Microsoft.KernelMemory.AI.OpenAI.OpenAITextEmbeddingGenerator
* Text generation     : Microsoft.KernelMemory.AI.OpenAI.OpenAITextGenerator
***************************************************************************************************************************

### Question

Examples are provided to upload a document using the web API.
Does the service exposes and API for ingesting web pages (ImportWebPageAsync)?

**Comment by ravijariwala** [comment]
I have a use case for importing HTML pages too. As far as I understand "Mime" type validation is ignoring such files. Only option for me now is to covert HTML to MD and then import the file.

**Comment by dluc** [comment]
@ravijariwala the service provides the entire API, you could use the Web client that implements all the API methods:

nuget: https://www.nuget.org/packages/Microsoft.KernelMemory.WebClient/
source: https://github.com/microsoft/kernel-memory/tree/main/clients/dotnet/WebClient

**Comment by dluc** [comment]
About HTML that's right there's never been an ask for it, but it would be very easy to add, 99% of the code would be in the [TextExtractionHandler](https://github.com/microsoft/kernel-memory/blob/main/service/Core/Handlers/TextExtractionHandler.cs)

**Comment by dluc** [comment]
Support for HTML files added in https://github.com/microsoft/kernel-memory/pull/327

The API is the same used for other file types, an example is available here https://github.com/microsoft/kernel-memory/tree/main/examples/003-dotnet-Serverless
