### ISSUE TITLE
[Bug] Handlers don't run in MemoryService mode with v0.29.240219.2

### ISSUE THREAD

**Issue by marcominerva** [microsoft/kernel-memory#319]
### Context / Scenario

After upgrading Kerner Memory NuGet package to v0.29.240219.2, the ingestion pipeline does not work anymore when using MemoryService. According to the log, it seems that Handlers are not registered at startup. If I revert back to 0.28.240212.1, everything works as expected.

This is the log of version 0.28.240212.1:

```
info: Microsoft.KernelMemory.Handlers.TextExtractionHandler[0]
      Handler 'extract' ready
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: extract
info: Microsoft.KernelMemory.Handlers.TextPartitioningHandler[0]
      Handler 'partition' ready
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: partition
info: Microsoft.KernelMemory.Handlers.GenerateEmbeddingsHandler[0]
      Handler 'gen_embeddings' ready, 1 embedding generators
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: gen_embeddings
info: Microsoft.KernelMemory.Handlers.SaveRecordsHandler[0]
      Handler save_records ready, 1 vector storages
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: save_records
info: Microsoft.KernelMemory.Handlers.SummarizationHandler[0]
      Handler 'summarize' ready
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: summarize
info: Microsoft.KernelMemory.Handlers.DeleteDocumentHandler[0]
      Handler 'private_delete_document' ready
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: private_delete_document
info: Microsoft.KernelMemory.Handlers.DeleteIndexHandler[0]
      Handler 'private_delete_index' ready
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: private_delete_index
info: Microsoft.KernelMemory.Handlers.DeleteGeneratedFilesHandler[0]
      Handler 'delete_generated_files' ready
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: delete_generated_files
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler service started: extract
```

If I just update the NuGet package to the last version, without any change to the code, these lines don't appear anymore in the log.

I have attached complete logs from both version, taken using this application: https://github.com/marcominerva/KernelMemoryService.

[v0.28.240212.1 - OK.log](https://github.com/microsoft/kernel-memory/files/14371290/v0.28.240212.1.-.OK.log)
[v0.29.240219.2 - Not working.log](https://github.com/microsoft/kernel-memory/files/14371291/v0.29.240219.2.-.Not.working.log)

### What happened?

The handlers must be registered also in MemoryService mode with the latest version of Kernel Memory NuGet package.

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

Language: C#
.NET: 8.0.2
Kernel Memory: 0.29.240219.2
IDE: Visual Studio 2022 17.9.1

**Comment by dluc** [comment]
Since version 0.29, the Web Service doesn't have a list of handlers hardcoded in C# anymore. The list is defined in `appsettings.json` and can be changed with your configuration files. This was necessary to reduce the need for rebuilding the service every time one needed to customize which handlers to deploy.

The `appsettings.json` file in the repo has the list of default handlers, and I would suggest upgrading that file => https://github.com/microsoft/kernel-memory/blob/main/service/Service/appsettings.json

![image](https://github.com/microsoft/kernel-memory/assets/371009/1e7eb800-4c1f-424b-b0b9-269fd2bd995c)

The list can be overridden with the usual environment config (appsettings.<env>.json).

Please note this code in https://github.com/microsoft/kernel-memory/blob/main/service/Service/Program.cs:

```csharp
// Register pipeline handlers if enabled
if (config.Service.RunHandlers)
{
    // You can add handlers in the configuration or manually here using one of these syntaxes:
    // appBuilder.Services.AddHandlerAsHostedService<...CLASS...>("...STEP NAME...");
    // appBuilder.Services.AddHandlerAsHostedService("...assembly file name...", "...type full name...", "...STEP NAME...");

    // Register all pipeline handlers defined in the configuration to run as hosted services
    foreach (KeyValuePair<string, HandlerConfig> handlerConfig in config.Service.Handlers)
    {
        appBuilder.Services.AddHandlerAsHostedService(config: handlerConfig.Value, stepName: handlerConfig.Key);
    }
}
```

and

```csharp
var memoryBuilder = new KernelMemoryBuilder(appBuilder.Services)
    .WithoutDefaultHandlers() // Note: handlers must be enabled via configuration in appsettings.json and/or appsettings.<env>.json
    .FromAppSettings();
```
