### ISSUE TITLE
Support the ability to inject `OpenAIClient` instance rather than a new one being created

### ISSUE THREAD

**Issue by aaronpowell** [microsoft/kernel-memory#320]
### Context / Scenario

The [.NET Aspire Preview 3 release](https://github.com/dotnet/aspire/discussions/2205) introduced an OpenAI/Azure OpenAI component, allowing you to set it up in the Aspire AppHost and use the component with Aspire managed connection details. [Here's a quick blog post on how to use it](https://www.aaron-powell.com/posts/2024-02-22-exploring-openai-with-aspire-preview-3/).

But this is incompatible with Kernel Memory as you have to provide it with the connection info, rather than inject an instance via DI.

This isn't unique to using Aspire though, it impacts any case where you want to share the `OpenAIClient` via DI in an application.

### The problem

Since the `WithAzureOpenAITextEmbeddingGeneration` and `WithAzureOpenAITextEmbeddingGeneration` don't support passing in an existing `OpenAIClient`, we can't leverage Aspire easily, nor are we able to provide much control over how the client is configured.

### Proposed solution

Have overloads to the DI methods that the AzureOpenAI extension provides that allows you to provide an `OpenAIClient` rather than the configuration details.

### Importance

would be great to have

**Comment by dluc** [comment]
#380 should address this, the custom OpenAIClient can be injected with `WithOpenAITextEmbeddingGeneration` and `WithOpenAITextGeneration`. If you have a chance to test please let us know.
