### ISSUE TITLE
[Bug] Incorrect Docker Volume Mapping in Documentation

### ISSUE THREAD

**Issue by Valkozaur** [microsoft/kernel-memory#323]
### Context / Scenario

While testing the Docker image locally, I found that the volume mapping instructions in the documentation are incorrect. The current instructions specify to map the local **appsettings.Development.json** to **/app/data/appsettings.Production.json** in the Docker container:
```
docker run --volume ./appsettings.Development.json:/app/data/appsettings.Production.json \
     -it --rm -p 9001:9001 kernelmemory/service

```
However, this does not correctly attach the volume to the Docker container, and the container does not recognize the development settings.
Upon inspecting the Docker image, I found that the actual folder structure in the container should be **/app/appsettings.Production.json**. 
After fixing the command, I was able to run the job successfully.
The current documentation may mislead others who are trying to run the service in their local environment. Therefore, I propose that we correct the volume mapping instructions both in the code comments and in the Docker image documentation.

### What happened?

**Steps to reproduce:**

1. Follow the current volume mapping instructions in the documentation.
2. Attempt to run the Docker container.
3. Observe that the volume does not attach correctly and the container does not recognize the development settings.

**Expected result:**
The Docker container should recognize the development settings when the volume is mapped correctly.

**Actual result:**
The Docker container does not recognize the development settings due to incorrect volume mapping instructions.
Environment:

Additional context:
The correct volume mapping command should be:
```
docker run --volume ./appsettings.Development.json:/app/appsettings.Production.json \
     -it --rm -p 9001:9001 kernelmemory/service

```

This issue requires updating the Docker volume mapping instructions in the documentation. I'm happy to create a pull request if someone could verify this issue.

### Importance

a fix would make my life easier

### Platform, Language, Versions

Docker version 24.0.7-rd
Windows 10

**Comment by cherchyk** [comment]
@Valkozaur, Please create a PR to fix documentation.

**Comment by cherchyk** [comment]
I created PR for documentation fix - https://github.com/microsoft/kernel-memory/pull/330
