### ISSUE TITLE
Microsoft.AspNetCore.Http.Abstractions is deprecated

### ISSUE THREAD

**Issue by marcominerva** [microsoft/kernel-memory#342]
### Context / Scenario

The **Core** project contains a reference to the `Microsoft.AspNetCore.Http.Abstractions` package: https://github.com/microsoft/kernel-memory/blob/main/service/Core/Core.csproj#L30. As we can read at https://github.com/dotnet/core/blob/main/release-notes/net-package-deprecation.md, this package has been deprecated.

### What happened?

Deprecated packages should not be used.

### Importance

edge case

### Platform, Language, Versions

Kernel Memory v0.30.240227.1

**Comment by marcominerva** [comment]
The recommended solution described at https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-8.0&tabs=visual-studio#use-the-aspnet-core-shared-framework is to use a `FrameworkReference `to the whole ASP.NET Core.

I agree that it isn't a great solution to add a dependecy to the entire ASP.NET Core to the **Core** project. Perhaps splitting the project and using `IFormFile`, `IFormFileCollection `and `HttpRequest `in a separated library that contains ASP.NET Core related features? In this case an abstraction over `IFormFile` and `IFormFileCollection` must be provided. It's just an idea ;)

**Comment by marcominerva** [comment]
Hi @dluc,

I have tried to split the features creating a new dedicated **WebService** library.

**Comment by dluc** [comment]
Does #411 introduce another nuget package? Is it worth the complexity, just to remove a warning? About the deprecated package, why is that a problem?

**Comment by marcominerva** [comment]
The package is deprecated, so for example it does not receive any security fix. Using the `FrameworkReference` is recommended by Microsoft itself: https://github.com/dotnet/aspnetcore/issues/50641.

**Comment by marcominerva** [comment]
Closed as completed by #411.
