### ISSUE TITLE
[Bug] Issue with default index name management

### ISSUE THREAD

**Issue by marcominerva** [microsoft/kernel-memory#349]
### Context / Scenario

Qdrant config has been updated to support default index name. However, there are some points in the **Abstractions** project that statically set the index name as `Constants.DefaultIndex` if it isn't provided.

### What happened?

The **Abstractions** project contains an [IndexExtensions.cs](https://github.com/microsoft/kernel-memory/blob/main/service/Abstractions/Models/IndexExtensions.cs) file that statically sets the index name to `Constants.DefaultIndex` if no name is set:

https://github.com/microsoft/kernel-memory/blob/61fb2b5789ba51543ab947a604dc8c1db3ac8bf1/service/Abstractions/Models/IndexExtensions.cs#L5-L14

This method is called
- In the `Index `property of the [DataPipeline.cs](https://github.com/microsoft/kernel-memory/blob/main/service/Abstractions/Pipeline/DataPipeline.cs) class:
https://github.com/microsoft/kernel-memory/blob/61fb2b5789ba51543ab947a604dc8c1db3ac8bf1/service/Abstractions/Pipeline/DataPipeline.cs#L213-L217
- In the constructor of the [DocumentUploadRequest.cs](https://github.com/microsoft/kernel-memory/blob/main/service/Abstractions/Models/DocumentUploadRequest.cs) class:
https://github.com/microsoft/kernel-memory/blob/61fb2b5789ba51543ab947a604dc8c1db3ac8bf1/service/Abstractions/Models/DocumentUploadRequest.cs#L76-L78

In this way, when running for example [SaveRecordsHandler.InvokeAsync](https://github.com/microsoft/kernel-memory/blob/main/service/Core/Handlers/SaveRecordsHandler.cs#L84): https://github.com/microsoft/kernel-memory/blob/61fb2b5789ba51543ab947a604dc8c1db3ac8bf1/service/Core/Handlers/SaveRecordsHandler.cs#L84-L95
`pipeline.Index` will always have a value (if not provided, it will statically be `Costants.DefaultIndex`, as shown above). 

As a result, the [QdrantMemory.NormalizeIndexName](https://github.com/microsoft/kernel-memory/blob/main/extensions/Qdrant/Qdrant/QdrantMemory.cs#L226-L236) method:

https://github.com/microsoft/kernel-memory/blob/61fb2b5789ba51543ab947a604dc8c1db3ac8bf1/extensions/Qdrant/Qdrant/QdrantMemory.cs#L226-L236

finds a value for `index`, so it will not set the `defaultIndex `name.

Every memory implementation (**Azure AI Search**, **Postregress**, **Qdrant**, **SimpleVectorDb**, **Redis**, etc.) contains a `NormalizeIndex` method that checks for its correct value, so I think that the [IndexExtensions.cs](https://github.com/microsoft/kernel-memory/blob/main/service/Abstractions/Models/IndexExtensions.cs) file can be safely removed.

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

Kernel Memory v0.32.240307.3

**Comment by dluc** [comment]
The issue should be solved now. The default index name is now a new global configuration setting, applied at the API level rather than internally in Qdrant only. The Qdrant setting has been removed.
