### ISSUE TITLE
[Bug] Documents duplicated with Qdrant

### ISSUE THREAD

**Issue by jerpic** [microsoft/kernel-memory#353]
### Context / Scenario

Hello,

I'm using Kernel-Memory with Qdrant and Azurestorage for the pipeline.

Everything works correctly, the documents (text content) are indexed correctly. When I modify a particular document, I delete it from the index and recreate it. I use the documentId which I pass to the API to the following methods to perform the actions.

`var tags = new TagCollection()
            {
                { "CATEGORY", item.Category.Label }
            };
            
            if (item.Indexed) // The item is already indexed ?
            {
                var isAlreadyIndexed = await _kernelMemory.IsDocumentReadyAsync(documentId:item.Indexid, index: _qdrantSettings.Index);
                if (isAlreadyIndexed)
                {
                    await _kernelMemory.DeleteDocumentAsync(documentId: item.Indexid, index: _qdrantSettings.Index);
                }
            }
  
            
            var docId = await  _kernelMemory.ImportTextAsync(item.Content, index:_qdrantSettings.Index,tags:tags);`
            
        
As I say, everything works fine except when I restart the application (session). In this case, the documentIds seem to no longer be recognized, and the documents are created several times on the Qdrant side.

### What happened?

après relance de l'application, les documentIds semblent ne plus être reconnu, en conséquence la réindexation d'un document existant se matérialise par un doublon.

### Importance

a fix would make my life easier

### Platform, Language, Versions

.NET7.0.

**Comment by marcominerva** [comment]
You don't need to delete the document when there is a change. Just call **ImportTextAsync** with the same **documentId** and it will be updated.

**Comment by dluc** [comment]
@jerpic Document IDs are stored in the "content storage", which can be:

* volatile memory (RAM)
* file system (disk)
* Azure blobs

Unless you configured differently, KM uses the volatile memory, so all the content storage disappears when the service is restarted. I would check the configuration, configuring the content storage to be either disk or Azure blobs.

**Comment by jerpic** [comment]
Hello @dluc,

Thank your for your response.

Here is my configuration. 

`
var kernelMemory = new KernelMemoryBuilder(builder.Services)
    .WithOpenAITextEmbeddingGeneration(new()
    {
        APIKey = kernelMemorySettings.ApiKey,
        EmbeddingModel = kernelMemorySettings.EmbeddingModel,
        EmbeddingModelMaxTokenTotal = 8191
    })
    .WithOpenAITextGeneration(new()
    {
        APIKey = kernelMemorySettings.ApiKey,
        TextModel = kernelMemorySettings.Model,
        TextModelMaxTokenTotal = 128_000
    })
    .WithQdrantMemoryDb(new QdrantConfig()
    {
        APIKey =  qdrantSettings.ApiKey,
        Endpoint = qdrantSettings.EndPoint
    })
    .WithCustomTextPartitioningOptions(new()
    {
        MaxTokensPerParagraph = 1000,
        MaxTokensPerLine = 300,
        OverlappingTokens = 100
    })
    .WithAzureQueuesOrchestration(new AzureQueuesConfig()
    {
        ConnectionString = azureQueueSettings.QueueConnectionString,
        Auth = AzureQueuesConfig.AuthTypes.ConnectionString
        
    })
    .Build<MemoryService>();  

builder.Services.AddSingleton<IKernelMemory>(kernelMemory);`

Could you tell me how configuring the content storage for the Document IDs ?

Regards

**Comment by jerpic** [comment]
> You don't need to delete the document when there is a change. Just call **ImportTextAsync** with the same **documentId** and it will be updated.

Hello @marcominerva,

Thanks for you response. With your one my code is simpler ;-)

**Comment by jerpic** [comment]
Thank you both for your help!
