### ISSUE TITLE
[Question]  TextExtractionHandler

### ISSUE THREAD

**Issue by xkzhud** [microsoft/kernel-memory#365]
### Context / Scenario

  when  the TextExtractionHandler running .   the  server cpu  rose from 0.6% to 46%.    when i use new MsWordDecoder().ExtractContent() .  the  cpu usage  almost no change.  

### Question

so, what is the difference and  do you  give some  suggestion?.   by  the way  .i use  KM with  serverless mode   and  my   service  deployed  in  cloud

**Comment by dluc** [comment]
Hi @xkzhud it's hard to say without knowing the exact nature of files and configuration of your infrastructure. I can only speculate that you might be dealing with files requiring that amount of CPU to be processed, e.g. the file type, the file size, something about the content in those files. I wouldn't worry about the CPU usage, unless it's staying over 80% for more than a minute. If import takes too long, you could try choosing bigger VMs to get a sense of what works better, or you could inspect the documents to see if they have anything special that could be hard to process.
