### ISSUE TITLE
SearchClient overwrites Citation state in SearchAsync

### ISSUE THREAD

**Issue by crickman** [microsoft/kernel-memory#37]
Lines 121-124 overwrite existing citation state.  For `Link`, `SourceContentType`, and `SourceName`  this will be assigning identical state, except in the case of multiple document import...in which caes `Link` will be last write wins.

For `Tags`, however, divergent states are assigned (reserved tags will be last write wins).

https://github.com/microsoft/semantic-memory/blob/main/dotnet/CoreLib/Search/SearchClient.cs

```
            // If the file is already in the list of citations, only add the partition
            var citation = result.Results.FirstOrDefault(x => x.Link == linkToFile);
            if (citation == null)
            {
                citation = new Citation();
                result.Results.Add(citation);
            }

            // Add the partition to the list of citations
            citation.Link = linkToFile;
            citation.SourceContentType = fileContentType;
            citation.SourceName = fileName;
            citation.Tags = memory.Tags;

#pragma warning disable CA1806 // it's ok if parsing fails
            DateTimeOffset.TryParse(memory.Payload[Constants.ReservedPayloadLastUpdateField].ToString(), out var lastUpdate);
#pragma warning restore CA1806

            citation.Partitions.Add(new Citation.Partition
            {
                Text = partitionText,
                Relevance = (float)relevance,
                LastUpdate = lastUpdate,
            });
```

**Comment by dluc** [comment]
about lines 121-124
```
citation.Link = linkToFile;
citation.SourceContentType = fileContentType;
citation.SourceName = fileName;
citation.Tags = memory.Tags;
```

> For Link, SourceContentType, and SourceName this will be assigning identical state, **except in the case of multiple document import...in which caes Link will be last write wins**.

Could you confirm you saw this happening?
If you look at these lines:

```
string linkToFile = $"{documentId}/{fileId}";
```
and
```
var citation = result.Results.FirstOrDefault(x => x.Link == linkToFile);
```

the citation being changed is one that matches `Link`. When uploading multiple files, the link will be different and the citation object being used will be different too.
