### ISSUE TITLE
[Bug] Package Common.Logging 1.2.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0).

### ISSUE THREAD

**Issue by kill136** [microsoft/kernel-memory#376]
### Context / Scenario

when i build docker images ,it come up a error 

Package Common.Logging 1.2.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0).

### What happened?

#28 69.34 /src/service/Service/Service.csproj : warning NU1701: Package 'ClosedXML 0.55.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0'. This package may not be fully compatible with your project.
#28 69.34 /src/service/Service/Service.csproj : warning NU1701: Package 'DocumentFormat.OpenXml 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0'. This package may not be fully compatible with your project.
#28 69.34 /src/service/Service/Service.csproj : warning NU1701: Package 'HtmlAgilityPack 1.3.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0'. This package may not be fully compatible with your project.
#28 69.36 /src/service/Service/Service.csproj : warning NU1701: Package 'MySql.Data 5.1.7' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0'. This package may not be fully compatible with your project.
#28 69.37 /src/service/Service/Service.csproj : warning NU1701: Package 'Quartz 1.0.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0'. This package may not be fully compatible with your project.
#28 69.39 /src/service/Service/Service.csproj : error NU1202: Package Common.Logging 1.2.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Common.Logging 1.2.0 supports: 10 (1.0,Version=v0.0)
#28 69.42   Failed to restore /src/service/Service/Service.csproj (in 51.88 sec).
#28 ERROR: process "/bin/sh -c dotnet restore \"./service/Service/Service.csproj\"" did not complete successfully: exit code: 1
------
 > [build 20/23] RUN dotnet restore "./service/Service/Service.csproj":
69.32 /src/service/Service/Service.csproj : warning NU1602: Microsoft.KernelMemory.Abstractions does not provide an inclusive lower bound for dependency System.Memory.Data. An approximate best match of System.Memory.Data 1.0.0 was resolved.
69.32 /src/service/Service/Service.csproj : warning NU1602: Microsoft.KernelMemory.Abstractions does not provide an inclusive lower bound for dependency System.Numerics.Tensors. An approximate best match of System.Numerics.Tensors 0.1.0 was resolved.
69.32 /src/service/Service/Service.csproj : warning NU1602: Microsoft.KernelMemory.Abstractions does not provide an inclusive lower bound for dependency System.Text.Json. An approximate best match of System.Text.Json 1.0.0 was resolved.
69.34 /src/service/Service/Service.csproj : warning NU1701: Package 'ClosedXML 0.55.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0'. This package may not be fully compatible with your project.
69.34 /src/service/Service/Service.csproj : warning NU1701: Package 'DocumentFormat.OpenXml 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0'. This package may not be fully compatible with your project.
69.34 /src/service/Service/Service.csproj : warning NU1701: Package 'HtmlAgilityPack 1.3.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0'. This package may not be fully compatible with your project.
69.36 /src/service/Service/Service.csproj : warning NU1701: Package 'MySql.Data 5.1.7' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0'. This package may not be fully compatible with your project.
69.37 /src/service/Service/Service.csproj : warning NU1701: Package 'Quartz 1.0.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0'. This package may not be fully compatible with your project.
69.39 /src/service/Service/Service.csproj : error NU1202: Package Common.Logging 1.2.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Common.Logging 1.2.0 supports: 10 (1.0,Version=v0.0)
69.42   Failed to restore /src/service/Service/Service.csproj (in 51.88 sec).
------
Dockerfile:26
--------------------
  24 |     COPY ["extensions/AzureQueues/AzureQueues.csproj", "extensions/AzureQueues/"]
  25 |     COPY ["extensions/Qdrant/Qdrant/Qdrant.csproj", "extensions/Qdrant/Qdrant/"]
  26 | >>> RUN dotnet restore "./service/Service/Service.csproj"
  27 |     COPY . .
  28 |     WORKDIR "/src/service/Service"
--------------------
ERROR: failed to solve: process "/bin/sh -c dotnet restore \"./service/Service/Service.csproj\"" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/default/default/utihg35hslbdyejtwvz79oehr

### Importance

edge case

### Platform, Language, Versions

windows 11 ,docker desktop  , vs sttdio  2022

**Comment by dluc** [comment]
@kill136 I just tried `docker build .` from the root of the repo and everything worked fine. As you can see from [Dockerfile](https://github.com/microsoft/kernel-memory/blob/main/Dockerfile) it's using .NET 7.

```
⚡️ docker build .
[+] Building 70.2s (21/21) FINISHED                                                                                                                                                                    docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                                                   0.0s
 => => transferring dockerfile: 1.89kB                                                                                                                                                                                 0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0-alpine                                                                                                                                            2.8s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:7.0-jammy                                                                                                                                                2.9s
 => [internal] load .dockerignore                                                                                                                                                                                      0.0s
 => => transferring context: 351B                                                                                                                                                                                      0.0s
 => [base 1/3] FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine@sha256:4be7f267bc80890df90024a7e1d143ba67f673f948b3ad75d69c5fd2bba86e6b                                                                                13.8s
 => => resolve mcr.microsoft.com/dotnet/aspnet:7.0-alpine@sha256:4be7f267bc80890df90024a7e1d143ba67f673f948b3ad75d69c5fd2bba86e6b                                                                                      0.0s
 => => sha256:2d3b6d5899cb4b80355572df34ab8d1f1cdeb50fc3157433caeff0d39e218715 9.82MB / 9.82MB                                                                                                                        13.6s
 => => sha256:28714363ef28a6a8c67264563e16305ab0dd07f98881cc4f05de77fc16b723ee 30.74MB / 30.74MB                                                                                                                      11.6s
 => => sha256:5a2bf890d1d02fd5a8dde8dc3d9c091c4190fe59030bcad6b226119c86c63be6 2.17MB / 2.17MB                                                                                                                         2.0s
 => => extracting sha256:5a2bf890d1d02fd5a8dde8dc3d9c091c4190fe59030bcad6b226119c86c63be6                                                                                                                              0.1s
 => => extracting sha256:28714363ef28a6a8c67264563e16305ab0dd07f98881cc4f05de77fc16b723ee                                                                                                                              0.3s
 => => extracting sha256:2d3b6d5899cb4b80355572df34ab8d1f1cdeb50fc3157433caeff0d39e218715                                                                                                                              0.1s
 => [internal] load build context                                                                                                                                                                                      0.5s
 => => transferring context: 35.40MB                                                                                                                                                                                   0.4s
 => [build 1/9] FROM mcr.microsoft.com/dotnet/sdk:7.0-jammy@sha256:e7878437b5a941a5be8cabee60435459161e4ef6ebf49757d733c1097620337a                                                                                   39.6s
 => => resolve mcr.microsoft.com/dotnet/sdk:7.0-jammy@sha256:e7878437b5a941a5be8cabee60435459161e4ef6ebf49757d733c1097620337a                                                                                          0.0s
 => => sha256:29f677c0e49e7ff8e06dc712df3cd8d6a83aa5a784fd40cbc811ea04cef2a01f 13.42MB / 13.42MB                                                                                                                       1.7s
 => => sha256:441510c88715470a5c57e0e6cb1f974fa218df0a0f266197979d3ec3780e3932 177.13MB / 177.13MB                                                                                                                    22.2s
 => => sha256:9606061d9e00251421939c8fe0cf393bfa80a09714825fde7411526a4bda2603 20.74MB / 20.74MB                                                                                                                      24.1s
 => => sha256:bd46bc458d59cde942ffc2d31842791623369cf22b996fd7a09dc4f3927410a7 9.82MB / 9.82MB                                                                                                                        11.3s
 => => sha256:f89bda80eadb9f68ab0bdd3f73b3822d34ad6b416c424036a185de1d39e4b90c 155B / 155B                                                                                                                             0.5s
 => => sha256:b8c9542d209a007d660946ca227263e6832ea24884218d9386ed447424069c86 30.73MB / 30.73MB                                                                                                                      22.4s
 => => sha256:1ad31ddc7130b1328785d9283989c95ea832781e8a523ffdb48527b8cdabb844 15.69MB / 15.69MB                                                                                                                      10.9s
 => => sha256:71dca2167f9f5ee82e602460098ce45ba714cb60cd683d677d994dad97c74bb2 28.40MB / 28.40MB                                                                                                                       3.3s
 => => extracting sha256:71dca2167f9f5ee82e602460098ce45ba714cb60cd683d677d994dad97c74bb2                                                                                                                              0.3s
 => => extracting sha256:1ad31ddc7130b1328785d9283989c95ea832781e8a523ffdb48527b8cdabb844                                                                                                                              0.1s
 => => extracting sha256:b8c9542d209a007d660946ca227263e6832ea24884218d9386ed447424069c86                                                                                                                              0.3s
 => => extracting sha256:f89bda80eadb9f68ab0bdd3f73b3822d34ad6b416c424036a185de1d39e4b90c                                                                                                                              0.0s
 => => extracting sha256:bd46bc458d59cde942ffc2d31842791623369cf22b996fd7a09dc4f3927410a7                                                                                                                              0.1s
 => => extracting sha256:9606061d9e00251421939c8fe0cf393bfa80a09714825fde7411526a4bda2603                                                                                                                              0.2s
 => => extracting sha256:441510c88715470a5c57e0e6cb1f974fa218df0a0f266197979d3ec3780e3932                                                                                                                              2.2s
 => => extracting sha256:29f677c0e49e7ff8e06dc712df3cd8d6a83aa5a784fd40cbc811ea04cef2a01f                                                                                                                              0.2s
 => [base 2/3] RUN     adduser -D -h /app -s /bin/sh km &&     chown -R km.km /app                                                                                                                                     0.3s
 => [base 3/3] WORKDIR /app                                                                                                                                                                                            0.0s
 => [final 1/2] WORKDIR /app                                                                                                                                                                                           0.0s
 => [build 2/9] WORKDIR /src                                                                                                                                                                                           0.2s
 => [build 3/9] COPY [service/Service/Service.csproj, service/Service/]                                                                                                                                                0.0s
 => [build 4/9] RUN dotnet restore "./service/Service/./Service.csproj"                                                                                                                                               17.1s
 => [build 5/9] COPY [extensions, extensions]                                                                                                                                                                          0.1s
 => [build 6/9] COPY [tools, tools]                                                                                                                                                                                    0.0s
 => [build 7/9] COPY [service, service]                                                                                                                                                                                0.0s
 => [build 8/9] WORKDIR /src/service/Service                                                                                                                                                                           0.0s
 => [build 9/9] RUN dotnet build "./Service.csproj" -c Release -o /app/build                                                                                                                                           5.1s
 => [publish 1/1] RUN dotnet publish "./Service.csproj" -c Release -o /app/publish /p:UseAppHost=false                                                                                                                 3.2s
 => [final 2/2] COPY --from=publish --chown=km:km --chmod=0550  /app/publish .                                                                                                                                         0.1s
 => exporting to image                                                                                                                                                                                                 1.8s
 => => exporting layers                                                                                                                                                                                                1.5s
 => => exporting manifest sha256:3946df589b15f573523f673c2a8d06d46e59eed4796da4a3d1a6daaa8f644a01                                                                                                                      0.0s
 => => exporting config sha256:0c9c21c743621613de71d03ac22a54ffda03e840dcff0401bc1c42b744b6365a                                                                                                                        0.0s
 => => exporting attestation manifest sha256:0be64c0b79c704195d1d18ea4915e4c9e06f16b078257163f6c0f68c762b2376                                                                                                          0.0s
 => => exporting manifest list sha256:397e526e93829625ca6ff033eccf0f6b8302ce7187101ea2b2dca1305a24876a                                                                                                                 0.0s
 => => naming to moby-dangling@sha256:397e526e93829625ca6ff033eccf0f6b8302ce7187101ea2b2dca1305a24876a                                                                                                                 0.0s
 => => unpacking to moby-dangling@sha256:397e526e93829625ca6ff033eccf0f6b8302ce7187101ea2b2dca1305a24876a
```
