### ISSUE TITLE
[Question] Package for MongoDB Atlas seems missing from nuget, Did I miss something in the PR?

### ISSUE THREAD

**Issue by alkampfergit** [microsoft/kernel-memory#378]
### Context / Scenario

I want to try new MongoDb Atlas support from nuget.

### Question

I've tried to search for the package for MongoDb ATlas in nuget but I did not found it. Did I miss something in the Pull Request to have it published in nuget?

**Comment by dluc** [comment]
hi @alkampfergit we haven't published the nuget yet, there's some testing we need to do, stay tuned :-)

**Comment by alkampfergit** [comment]
Ok thanks :), I just want to be sure that I've done everything from my part :).

**Comment by dluc** [comment]
Fixed: https://www.nuget.org/packages/Microsoft.KernelMemory.MongoDbAtlas
