### ISSUE TITLE
[Feature Request] Configure Decoders with Dependency Injection

### ISSUE THREAD

**Issue by marcominerva** [microsoft/kernel-memory#379]
### Context / Scenario

This is related to https://github.com/microsoft/kernel-memory/issues/375. If we want to customize how content is extracted, we can create a new implementation of the [TextExtractionHandler](https://github.com/microsoft/kernel-memory/blob/main/service/Core/Handlers/TextExtractionHandler.cs). However, in most cases, the default handler is fine, and we just need to customize how the text is actually retrieved (i.e., applying some custom processing).

### The problem

Currently, **Decoders** are explicitly created in the [TextExtractionHandler.InvokeAsync](https://github.com/microsoft/kernel-memory/blob/main/service/Core/Handlers/TextExtractionHandler.cs#L55) method. So, if we want to customize the extraction step for a particular file type (or even add support for a new file type), the only way is to provide a whole implementation of the `TextExtractionHandler` itself.

### Proposed solution

If **Decoders** are registered in the Service Collection, it will be easy to define a custom implementation for a particular MIME type (for example, if we want to customize how text is extracted from a PDF file), without the need to redefine the whole handler.

Of course, this won't introduce any breaking change, because current **Decoders** will be registered as default, but we can easily create our own if needed.

Moreover, with this approach, we can dynamically add support for new file types just adding a new registration in the Service Collection, without touching the `TextExtractionHandler` at all.

@dluc, If you think that this feature is interesting, I will be more than happy to take care of the PR 😀

### Importance

would be great to have

**Comment by dluc** [comment]
I see the benefits, before jumping to it, could you describe what approach you would take, e.g. in terms of classes and interfaces?

**Comment by marcominerva** [comment]
Sure!

I was thinking about adding an interface in the `Abstractions` project like the following (with `async` methods to handle all the scenarios):

```csharp
public interface IDecoder
{
    IEnumerable<string> SupportedMimeTypes { get; }

    Task<FileContent> ExtractContentAsync(string filename);

    Task<FileContent> ExtractContentAsync(BinaryData data);

    Task<FileContent> ExtractContentAsync(Stream data);
}
```

Then, an extension method for the `KernelMemoryBuilder`:

```csharp
public static IKernelMemoryBuilder WithDecoder<T>(this IKernelMemoryBuilder builder) where T : class, IDecoder
{
    builder.Services.AddSingleton<IDecoder, T>();
    return builder;
}
```

So, the `TextExtractionHandler` takes in the constructor the collection of Decoders:

```csharp
public TextExtractionHandler(
    string stepName,
    IPipelineOrchestrator orchestrator,
    IEnumerable<IDecoder> decoders,
    IOcrEngine? ocrEngine = null,
    ILogger<TextExtractionHandler>? log = null)
```

In this way, the Decoder can be selected with something like this:

```csharp
private async Task<(string text, FileContent content, string extractType, bool skipFile)> ExtractTextAsync(
    DataPipeline.FileDetails uploadedFile,
    BinaryData fileContent,
    CancellationToken cancellationToken)
{
    // ...

    var decoder = this._decoders.LastOrDefault(d => d.SupportedMimeTypes.Contains(uploadedFile.MimeType));
    if (decoder is not null)
    {
        content = await decoder.ExtractContentAsync(fileContent, cancellationToken).ConfigureAwait(false);
    }

    // ...
}
```

NOTE: Instead of an interface `IDecoder`, we could create a base `Decoder` class, to define default implementation for the `GetContentAsync` overloads that take a _filename_ and a _BinaryData_ input.

**Comment by marcominerva** [comment]
Hi @dluc!

Do you agree with my approach?

**Comment by dluc** [comment]
how is `IEnumerable<IDecoder> decoders` resolved?

**Comment by marcominerva** [comment]
If we register multiple implementations of the same instance, there will be automatically exposed by the Service Provider as an `IEnumerable`:

```csharp
builder.Services.AddSingleton<IDecoder, PdfDecoder>();
builder.Services.AddSingleton<IDecoder, MsWordDecoder>();
```

**Comment by dluc** [comment]
Naming-wise, I'd go with `IContentDecoder` and `WithContentDecoder`, allowing also to pass instances instead of `<T>` , considering that some decoders are configurable via ctor params. 

There's also some work to do to align `ExtractContent` across the decoders, e.g. see `MsPowerPointDecoder`.

If there are two decoders that support the same file types, I would log a warning, perhaps consider throwing an exception.

**Comment by marcominerva** [comment]
Using `T` instead of instances allows to leverage dependency injection in decoders, for example if we want to use `IHttpClientFactory`. In this case, parameters can be just another object that is itself registered in the Service Collection.

For what concerns two decoders that support the same file types, I think that we need to use the last registered, because in this way we can overwrite any default registration. Of course, we can log this situation, but not throw an Exception.

**Comment by dluc** [comment]
sure, I mean I would support both `<T>` and passing an instance, leaving both the doors open

**Comment by marcominerva** [comment]
OK, got it. So, do you think I can start with the implementation of my ideas and make a PR?

**Comment by dluc** [comment]
> OK, got it. So, do you think I can start with the implementation of my ideas and make a PR?

yes, looking forward to seeing it 👍

**Comment by marcominerva** [comment]
@dluc, I have a question for  you. In the `ExtractTextAsync `method of **TextExtractionHandler.cs** (https://github.com/microsoft/kernel-memory/blob/main/service/Core/Handlers/TextExtractionHandler.cs#L128), You initially set the `extractType` variable to `MimeTypes.PlainText`. 

https://github.com/microsoft/kernel-memory/blob/489e4c66f96b0f3f4320d140a46d69fa65a1a26a/service/Core/Handlers/TextExtractionHandler.cs#L135

Then, you redefine its value only in case of **MarkDown**:

https://github.com/microsoft/kernel-memory/blob/489e4c66f96b0f3f4320d140a46d69fa65a1a26a/service/Core/Handlers/TextExtractionHandler.cs#L144-L148

In all the other cases, it remains `MimeTypes.PlainText`. Why is this step necessary?

**Comment by dluc** [comment]
> In all the other cases, it remains `MimeTypes.PlainText`. Why is this step necessary?

It has to do with the text chunker logic. MarkDown is a special format of plain text where new lines `\n` have a different meaning. 

For instance, in plain text files one would never add a new line, unless a sentence is complete with some punctuation like `.`, `?`, `!` etc. And even in this scenario a new line is not mandatory. We use this approach for all types except markdown, although it could be improved, e.g. when working with Excel there's no punctuation and it would be better having a clear separation between lines.

In markdown files, new lines are very common for the sake of readability, e.g. adding a new line after 76 chars, 80 chars or 120 chars, there's many different approaches. A new line can be in the middle of a sentence, and MD renderers just ignore them. However, 2 consecutive new lines have a clear meaning, they are rendered as separate blocks, ie as separate sentences, regardless of punctuation.

The text chunker in the repo implements two slightly different chunking approaches, considering new lines differently, depending on the mime type.

**Comment by dluc** [comment]
I rather not change how mime type is handled right now, and leave the mime type handling as it is, in the handler. I don't think we should make it a bigger thing than it already is and it seems out of scope with the goal of enabling dependency injection. 

The current goal of text extractors is to return blocks of texts, organized as a graph, but there's more work to do in future. E.g. you might have noticed that extractors return a list of sections, currently used only for pages. In future we might extend sections to be blocks of different mime types, e.g. extracting text, images and more, which multi-modal LLMs will be able to process eventually. In other words, currently we handle mime type at the file level, only for the sake of chunking, but in future, a file will be able to be seen as a collection of multiple chunks of different mime types. Since the topic is still vague and LLM support for multi-modal is very early, I'd leave it unchanged.

**Comment by dluc** [comment]
Merged and shipped. While working on this I found/fixed a bug in the Excel decoder.
