### ISSUE TITLE
[Bug] Endless waiting with custom openAI endpoint

### ISSUE THREAD

**Issue by JonathanVelkeneers** [microsoft/kernel-memory#388]
### Context / Scenario

I am trying to use the new functionality to use a custom openAI endpoint provided by #380.
I'm attempting to use a HuggingFace model that supports chat through their interference API ([example](https://huggingface.co/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO) & [documentation](https://huggingface.co/blog/tgi-messages-api#using-inference-endpoints-with-openai-client-libraries)).

Using cUrl the result is as I expected:
**Request:**
```
curl -N https://api-inference.huggingface.co/models/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO/v1/chat/completions \
    -X POST \
    -d '{"model":"NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO", "messages": [{"role":"user","content":"How is the weather in Antwerp, Belgium?"}]}' \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```
    
**Response:**
```
{"id":"","object":"text_completion","created":1711630137,"model":"text-generation-inference/Nous-Hermes-2-Mixtral-8x7B-DPO-medusa","system_fingerprint":"1.4.3-sha-e6bb3ff","choices":[{"index":0,"message":{"role":"assistant","content":"As an AI, I do not have real-time access to weather information. However, I can give you weather forecasts and updates by using external APIs or services that provide weather data. Here's a sample forecast for Antwerp, Belgium from a popular weather API:\n\nToday:\nAntwerp, Belgium\n\nPartly cloudy with a high of 22°C (72°F) and a low of 10°C (50°"},"logprobs":null,"finish_reason":"length"}],"usage":{"prompt_tokens":20,"completion_tokens":100,"total_tokens":120}}%
```

However, when using it in Kernel-Memory it hangs indefinitely.
This is how it is configured in my Program.cs:
```
var huggingFaceConfig = new OpenAIConfig
{
    Endpoint = "https://api-inference.huggingface.co/models/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO/v1",
    TextModel = "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO",
    TextModelMaxTokenTotal = 4096,
    TextGenerationType = OpenAIConfig.TextGenerationTypes.Chat,
    APIKey = "XXXXXXXXXXXXXXXXXXXXXXXXXX"
};

var memoryConnector = new KernelMemoryBuilder(builder.Services)
    .WithOpenAITextEmbeddingGeneration(openAiConfig)
    .WithOpenAITextGeneration(huggingFaceConfig)
    .WithPostgresMemoryDb(Env.Var("POSTGRES_CONNECTION"))
    .WithSearchClientConfig(searchClientConfig)
    .WithCustomPromptProvider(new CustomMemoryPromptProvider())
    .Build<MemoryServerless>();
```

Running following code hangs endlessly:
`var memoryAnswer = await _kernelMemory.AskAsync(message, index: index, minRelevance: 0.35);`
When providing a wrong model, or wrong API key, the response is also as expected a 404 or a 403.

I dug a little deeper to see why nothing was happening.
When running a debugger on OpenAITextGenerator.cs:179 it shows that the following line of code contains a status code 200.
```
StreamingResponse<StreamingChatCompletionsUpdate>? response = await this._client.GetChatCompletionsStreamingAsync(openaiOptions, cancellationToken).ConfigureAwait(false);
```

When debugging the foreach-loop on OpenAITextGenerator.cs:181 it shows that in the first iteration it yields a "NULL" value, and after that it never yields anything again.
```
await foreach (StreamingChatCompletionsUpdate? update in response.EnumerateValues().WithCancellation(cancellationToken).ConfigureAwait(false))
{
    yield return update.ContentUpdate;
}
```

I believe this might be an issue with buffering/streaming as the cUrl command also return the whole response at once even with the -N param added. My technical knowledge on these topics is limited however.

### What happened?

`var memoryAnswer = await _kernelMemory.AskAsync(message, index: index, minRelevance: 0.35);`
This should yield normal results when using a custom openAI endpoint as if using openAI's own endpoint.
Currently this results in a task infinitely hanging.

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

- MacOS ARM64
- Dotnet 8.0
- Microsoft.KernelMemory.Core 0.35.240321.1

### Relevant log output

```shell
trce: Microsoft.KernelMemory.Search.SearchClient[0]
      Fetching relevant memories
info: Microsoft.SemanticKernel.Connectors.OpenAI.OpenAITextEmbeddingGenerationService[0]
      Action: GenerateEmbeddingsAsync. OpenAI Model ID: text-embedding-3-large.
trce: Microsoft.KernelMemory.Search.SearchClient[0]
      Adding text 1 with relevance 0.7604556251387263
trce: Microsoft.KernelMemory.Search.SearchClient[0]
      Adding text 2 with relevance 0.709515102419009
trce: Microsoft.KernelMemory.Search.SearchClient[0]
      Adding text 3 with relevance 0.39204232597858146
dbug: Microsoft.KernelMemory.Search.SearchClient[0]
      Running RAG prompt, size: 2529 tokens, requesting max 1000 tokens
```

**Comment by dluc** [comment]
Looks like the endpoint is not streaming the result, we'll have to check why that might be a problem

**Comment by JonathanVelkeneers** [comment]
> Looks like the endpoint is not streaming the result, we'll have to check why that might be a problem

@dluc 
In my original cUrl request test i forgot the stream:true property, so it was not streamed.
With the following command streaming was succesfull:

```
curl -N https://api-inference.huggingface.co/models/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO/v1/chat/completions \
    -X POST \
    -d '{"model":"NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO", "stream": true, "messages": [{"role":"user","content":"How is the weather in Antwerp, Belgium?"}], "parameters": {"temperature": 0.7, "max_new_tokens": 100}}' \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXX"
```

So the endpoints on HuggingFace's end should be streaming correctly.

**Comment by dluc** [comment]
As per https://github.com/huggingface/text-generation-inference/issues/1582 looks like HuggingFace doesn't like top_p == 0. 

Also the API response is broken, returning 200 instead of 400. The combination of 200 plus incorrect payload causes the internal client to get stuck.

```
curl -v -X POST  https://api-inference.huggingface.co/models/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO/v1/chat/completions \
    -H "Authorization: Bearer hf_............." \
    -H "Content-Type: application/json" \
    -d '{"messages":[{"content":"how much is 1+1","role":"system"}],
      "max_tokens":100,"temperature":0,
      "top_p":0,
      "presence_penalty":0,
      "frequency_penalty":0,
      "stream":true,
      "model":"NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO"}'
```

```
< HTTP/2 200
< date: Tue, 14 May 2024 03:16:34 GMT
< content-type: text/event-stream
< content-length: 100
< x-sha: .........
< vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
< x-request-id: .........
< access-control-allow-credentials: true
< x-compute-type: cache
<
data:{"error":"Input validation error: `top_p` must be > 0.0 and < 1.0","error_type":"validation"}
```

**Comment by dluc** [comment]
This workaround unblocks the token generation:

```
.WithSearchClientConfig(new SearchClientConfig { TopP = 0.01 })
```

However, there might be other problems, e.g. the termination doesn't seem to stop correctly after max_tokens, so we might need a patch to manually watch the number of tokens generated

**Comment by dluc** [comment]
Looks like HF endpoint is not fully compatible with OpenAI, so OpenAI clients (at least the one in Azure SDK) don't work.

Unless the HF team fixes/changes the web service on their end, I'm afraid there's not much we can do about it. 

I reported the issue here https://github.com/huggingface/text-generation-inference/issues/1896, I would suggest to vote and follow up with HF.
