### ISSUE TITLE
[Feature Request] Allow custom WebScraper

### ISSUE THREAD

**Issue by JonathanVelkeneers** [microsoft/kernel-memory#395]
### Context / Scenario

using MemoryServerless I would like to be able to customise webscraping logic to utilise certain css selectors so semantics can be improved by excluding navs, footer, and other non-content.

### The problem

It is currently not possible to customise webscraping logic without completely overriding the TextExtractionHandler ingestion step.

### Proposed solution

I believe the easiest way to get this implemented is make an interface IWebScraper available and make the current WebScraper implement it.
Then allow injecting a custom WebScraper through DI. 
For example:

```
var memoryConnector = new KernelMemoryBuilder(builder.Services)
    .WithOpenAI(openAiConfig)
    .WithPostgresMemoryDb(Env.Var("POSTGRES_CONNECTION"))
    .WithSearchClientConfig(searchClientConfig)
    .WithCustomPromptProvider(new CustomMemoryPromptProvider())
    .WithCustomWebScraper(new CustomWebScraper())
    .Build<MemoryServerless>();
```
Which could be implemented like so:
```
public static IKernelMemoryBuilder WithCustomWebScraper(this IKernelMemoryBuilder builder, IWebScraper service)
{
    service = service ?? throw new ConfigurationException("The web scraper instance is NULL");
    builder.AddSingleton<IWebScraper>(service);
    return builder;
}
```

I am willing to make a PR for this feature

### Importance

would be great to have

**Comment by marcominerva** [comment]
I think this scenario could be realized after implementing the feature proposed at https://github.com/microsoft/kernel-memory/issues/379.

**Comment by dluc** [comment]
@JonathanVelkeneers would this work https://github.com/microsoft/kernel-memory/pull/407 ? I haven't tested it yet, but it should provide the basic building block.

**Comment by JonathanVelkeneers** [comment]
> @JonathanVelkeneers would this work #407 ? I haven't tested it yet, but it should provide the basic building block.

Exactly what I was looking for, PR looks good at a glance!

**Comment by dluc** [comment]
Shipped 👍
