### ISSUE TITLE
[Bug] Using Azure AI Search Memory DB, Error 503 is returned when a document comprises many partitions

### ISSUE THREAD

**Issue by pedershk** [microsoft/kernel-memory#426]
### Context / Scenario

When uploading large documents (PDFs) (a few hundred pages) with a partition size of 1200 tokens, the Azure AI Search service is overwhelmed and returns error 503, indicating too many requests are sent in too short a timespan. It's not possible to scale out of this error - increasing the number of partitions and/or replicas has no effect.

### What happened?

Import is halted with only a fraction of partitions actually added to AI Search index. It would be very useful to set a max number of requests per minute/second on adding AzureAiSearchMemoryDB to the KernelBuilder. Even better would be a backoff/retry mechanism that has an internal RPM counter which it automatically tunes down.

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

KM version 0.37

**Comment by pedershk** [comment]
This might be a relevant code snippet: https://github.com/microsoft/kernel-memory/blob/ce815a04b4ca61aa75498e28042e42bd294fe506/extensions/AzureAISearch/AzureAISearch/AzureAISearchMemory.cs#L349

```
  foreach (MemoryRecord record in records)
        {
            var localRecord = AzureAISearchMemoryRecord.FromMemoryRecord(record);
            await client.IndexDocumentsAsync(
                IndexDocumentsBatch.Upload(new[] { localRecord }),
                new IndexDocumentsOptions { ThrowOnAnyError = true },
                cancellationToken: cancellationToken).ConfigureAwait(false);

            yield return record.Id;
        }
```

The IndexDocumentsBatch can be loaded with several records - but here each individual record is uploaded individually, creating pressure on the underlying AI Search service. Batching this up (I don't know what would be an appropriate batch size, though) as the name IndexDocumentsBatch indicates might be a simple fix to the problem.

**Comment by marcominerva** [comment]
I think we can rewrite the method with chunking:

```csharp
private async IAsyncEnumerable<string> UpsertBatchAsync(
    string index,
    IEnumerable<MemoryRecord> records,
    [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
    var client = this.GetSearchClient(index);

    foreach (var recordChunk in records.Chunk(_batchSize))
    {
        var localRecords = recordChunk.Select(AzureAISearchMemoryRecord.FromMemoryRecord);

        await client.IndexDocumentsAsync(
            IndexDocumentsBatch.Upload(localRecords),
            new IndexDocumentsOptions { ThrowOnAnyError = true },
            cancellationToken: cancellationToken).ConfigureAwait(false);

        foreach (var record in recordChunk)
        {
            yield return record.Id;
        }
    }
}
```

In this example, I'm using a local variable `_batchSize`, but we can add it to `AzureAISearchConfig` so that everyone can set the appropriate value.

@dluc, if you're agree with this change, I can take care of the PR.

**Comment by pedershk** [comment]
For additional context - I'm not entirely sure when and at what rate limit the 503 error occurs - but most tests I've run seem to hit the trigger after about 300-400 IndexDocumentsAsync calls. I'm on a gigabit connection to a geographically close Region hosting the AI Search instance - and these are sent within less than a minute. It seems likely that staying below 250-300 requests per minute is safe.  

Having the batchSize be configurable would be great. According to the (REST API) documentation, it's limited to 1000 documents or 16MB of documents per batch : https://learn.microsoft.com/en-us/rest/api/searchservice/addupdate-or-delete-documents

**Comment by dluc** [comment]
optimizations aside, @pedershk are you using the async memory with retry queues?

**Comment by pedershk** [comment]
> optimizations aside, @pedershk are you using the async memory with retry queues?

Not entirely sure what you're referring to. Is this one of the parts that needs external integration to for instance Rabbit MQ? If yes, then no, we're not. We're using Kernel Memory as part of a large solution where KM plays one part - and I'm trying to keep "KM-specific" infrastructure to a minimum.

If you're referring to something else, please let me know.

Here's how we set up KM:

```
public static class KernelMemoryExtensions
{

    private const int PartitionSize = 1200;
    private const int MaxTokensPerLine = 100;

    public static IHostApplicationBuilder AddKeyedKernelMemoryForDocumentProcess(this IHostApplicationBuilder builder, ServiceConfigurationOptions serviceConfigurationOptions, DocumentProcessOptions documentProcessOptions, string key = null)
    {
        var sp = builder.Services.BuildServiceProvider();
        var openAi = sp.GetKeyedService<OpenAIClient>("openai-planner");
        var baseSearchClient = sp.GetService<SearchIndexClient>();

        if (string.IsNullOrEmpty(key) && !string.IsNullOrEmpty(documentProcessOptions.Name))
        {
            key = documentProcessOptions.Name;
        }

        if (string.IsNullOrEmpty(key))
        {
            throw new ArgumentException("Key must be provided or Document Process must have a valid name");
        }

        var openAiConnString = builder.Configuration.GetConnectionString("openai-planner");
        
        // Get Endpoint from Connection String
        var openAiEndpoint = openAiConnString!.Split(";").FirstOrDefault(x => x.Contains("Endpoint="))?.Split("=")[1];
        // Get Key from Connection String
        var openAiKey = openAiConnString!.Split(";").FirstOrDefault(x => x.Contains("Key="))?.Split("=")[1];

        var openAiEmbeddingConfig = new AzureOpenAIConfig()
        {
            Auth = AzureOpenAIConfig.AuthTypes.APIKey,
            Endpoint = openAiEndpoint,
            APIKey = openAiKey,
            Deployment = serviceConfigurationOptions.OpenAi.EmbeddingModelDeploymentName,
            APIType = AzureOpenAIConfig.APITypes.EmbeddingGeneration
        };

        var openAiChatCompletionConfig = new AzureOpenAIConfig()
        {
            Auth = AzureOpenAIConfig.AuthTypes.APIKey,
            Endpoint = openAiEndpoint,
            APIKey = openAiKey,
            Deployment = serviceConfigurationOptions.OpenAi.GPT4128KModelDeploymentName,
            APIType = AzureOpenAIConfig.APITypes.ChatCompletion
        };

        var azureAiSearchConfig = new AzureAISearchConfig()
        {
           Endpoint = baseSearchClient.Endpoint.AbsoluteUri,
           Auth = AzureAISearchConfig.AuthTypes.ManualTokenCredential
        };

        azureAiSearchConfig.SetCredential(new DefaultAzureCredential());
        

        var textPartitioningOptions = new TextPartitioningOptions
        {
            MaxTokensPerParagraph = PartitionSize,
            MaxTokensPerLine = MaxTokensPerLine,
            // No Overlap is important because we grab before and after segments for context
            OverlappingTokens = 0,
        };

        var kernelMemoryBuilder = new KernelMemoryBuilder()
            .WithAzureOpenAITextEmbeddingGeneration(openAiEmbeddingConfig)
            .WithAzureOpenAITextGeneration(openAiChatCompletionConfig)
            .WithCustomTextPartitioningOptions(textPartitioningOptions)
            .WithAzureAISearchMemoryDb(azureAiSearchConfig);
            
        // Add Logging
        kernelMemoryBuilder.Services.AddLogging(l =>
        {
            l.AddConsole().SetMinimumLevel(LogLevel.Information);
            l.AddConfiguration(builder.Configuration);
        });

        var kernelMemory = kernelMemoryBuilder.Build();

        builder.Services.AddKeyedSingleton<IKernelMemory>(documentProcessOptions.Name+"-IKernelMemory", kernelMemory);
        
        return builder;
    }
}
```

We have one KM, registered in DI as a Keyed Singleton, per "Document Process" in our solution. This runs horizontally scaled out on containerized workers.

**Comment by dluc** [comment]
I see, so you're using the embedded serverless option. One way to scale KM horizontally and handle transient errors would be to deploy KM as a service, and in your code replace:

```csharp
IKernelMemory kernelMemory = kernelMemoryBuilder.Build();
```

with

```csharp
IKernelMemory kernelMemory = new MemoryWebClient("<km endpoint>"); 
```

KM as a service uses queues to deal with the sort of problems you're facing. Even if the code is optimized, there will always be cases where there are too many requests, or the something in Azure is down, or something else fails - that's where KM queues handle the retry automatically.

**Comment by pedershk** [comment]
Yes - because we have to configure it dynamically based on many different indexes and document types each owning their own KM/AiSesrch index.

We scale horizontally in that these workers pull messages from queues - never more than 1 concurrently each. For us, using the service route would introduce more complexity, not less.

We have retry functionality at the outer edge of this, but we'd be hitting the same problem over and over.

Anyhow - this particular problem is tied to processing a single document at a time - not in any form of horizontal scale out (I think?).

It would probably still be good practice to not overwhelm the backend.

**Comment by marcominerva** [comment]
In any case, document batching can be a great improvement, as suggested in the [documentation](https://learn.microsoft.com/en-us/rest/api/searchservice/addupdate-or-delete-documents):

> For a large update, batching [...] is recommended and will significantly improve indexing performance.

We can set the default batch size to 1 to keep the current behavior as default. What do you think @dluc?

**Comment by pedershk** [comment]
> We can set the default batch size to 1 to keep the current behavior as default. What do you think @dluc?

From my end that's fine as long as it can be set - but would you really want to set it to 1 by default? Combined with typical small partition sizes used by KM, that generates a looot of requests against Azure AI Search.  Even setting it to 2 or 3 would likely make this issue go away for a lot of use cases. Anyway - not my call :)

**Comment by dluc** [comment]
iterating on improvements is always good, looks like a quick win :-)

**Comment by pedershk** [comment]
Any timeline on a fix/release, or should I fork and create a "custom" AI Search provider for our needs in the mean time?

**Comment by marcominerva** [comment]
After digging in the code, I found that the [AzureAISearchMemory.UpsertBatchAsync](https://github.com/microsoft/kernel-memory/blob/main/extensions/AzureAISearch/AzureAISearch/AzureAISearchMemory.cs#L356) is actually never called. The `SaveRecordsHandlers` always call [UpsertAsync](https://github.com/microsoft/kernel-memory/blob/main/extensions/AzureAISearch/AzureAISearch/AzureAISearchMemory.cs#L127) on memory.

So, I have tried adding an `IBatchMemoryDb` to define Memories that support batching (like AI Search) and I have modified the `SaveRecordsHandler` to support this new feature. I have made some tests with Azure AI Search and it seems to work, moreover in this way we can easily adding batch to all memories.

**Comment by pedershk** [comment]
Any update @marcominerva and @dluc - I see the PR isn't quite closed yet.

**Comment by marcominerva** [comment]
@pedershk, the PR has been merged: https://github.com/microsoft/kernel-memory/pull/438. I think the NuGet package will be updated soon too.

**Comment by dluc** [comment]
Version 0.51.240513.2 ready with the improvements from #438

**Comment by pedershk** [comment]
Not to beat the "dead issue" here, but I just want to extend a big thank you to both @marcominerva and @dluc for your work on this - it solved all our problems, we're now happily batching partitions/documents (20 or 30 depending on size), performance has significantly improved, and we have no errors. we're even able to distribute work across multiple containers in parallel and still hit no 503 errors.

THANK YOU!
