### ISSUE TITLE
[Bug] MsExcelDecoder.DecodeAsync only works on text data types

### ISSUE THREAD

**Issue by owen-barbour** [microsoft/kernel-memory#447]
### Context / Scenario

MsExcelDecoder.DecodeAsync only decodes columns that are of type "XLDataType.Text". The cell value output for non-text types, for example a number, is an empty string.

See https://github.com/microsoft/kernel-memory/blob/a48779339719e38d0aa0cbb423365d0c99bf1c1d/service/Core/DataFormats/Office/MsExcelDecoder.cs#L79-L81

I am using IKernelMemory.ImportDocumentAsync. Tracing the call, it seems BaseOrchestrator's default pipeline ingestion steps contains PipelineStepsExtract, thus invoking the TextExtractionHandler.ExtractTextAsync and then MsExcelDecoder.DecodeAsync.

### What happened?

I would expect MsExcelDecoder.DecodeAsync to include a string representation of any cell value. It instead only includes cell values that are ClosedXML.Excel's type XLDataType.Text. I also tried with the sample xlsx file (https://github.com/microsoft/kernel-memory/blob/a48779339719e38d0aa0cbb423365d0c99bf1c1d/examples/205-dotnet-extract-text-from-docs/msexcelfile.xlsx) and experienced the same issues. 

A possible solution would be to use IXLCell.Value.ToString() (https://github.com/ClosedXML/ClosedXML/blob/02fcf73e2992fa2589cdf2781007d109cac55cd9/ClosedXML/Excel/XLCellValue.cs#L376-L395).

### Importance

edge case

### Platform, Language, Versions

Using .NET 6 with version 0.36.240416.1

**Comment by dluc** [comment]
Thanks for the report! Bug fixed
