### ISSUE TITLE
[Question] Why does StreamAsync is a property (instead of a GetStreamAsync method)?

### ISSUE THREAD

**Issue by marcominerva** [microsoft/kernel-memory#452]
### Context / Scenario

I'm trying the new download feature of Kernel Memory in a simple console application:

```csharp
using var streamableFileContent = await kernelMemory.ExportFileAsync(documentId, fileName);
var stream = await streamableFileContent.StreamAsync();
```

### Question

I'm wondering why [StreamAsync](https://github.com/microsoft/kernel-memory/blob/main/service/Abstractions/Models/StreamableFileContent.cs#L17) on [StreamableFileContent](https://github.com/microsoft/kernel-memory/blob/main/service/Abstractions/Models/StreamableFileContent.cs) is defined as a property, because I think that a method like `GetStreamAsync()` would be more intuitive.

**Comment by dluc** [comment]
good point, I also plan to revisit the new method to see if we can use FileInfo. We might not need the `StreamableFileContent` class

**Comment by dluc** [comment]
method renamed. About FileInfo, something for the future
