### ISSUE TITLE
[Question] Support for C# 12

### ISSUE THREAD

**Issue by marcominerva** [microsoft/kernel-memory#455]
### Context / Scenario

With the removing of .NET Standard compatibility (see https://github.com/microsoft/kernel-memory/commit/5fcae7b645c1ad6ddd7a909a6f97fae2c801d1e3), now all the projects target .NET 8.0. But, in the `Directory.Build.props` file, the `LangVerson `is still set to v11:

https://github.com/microsoft/kernel-memory/blob/6d813c1da6e914dc70e58b822f487231a656d4f3/Directory.Build.props#L10

### Question

Is it now possible to switch to C# 12?

**Comment by marcominerva** [comment]
I was mainly thinking about collection expressions to avoid repetitive code :) And also the spread operator can be useful, but depends on the scenario.

**Comment by dluc** [comment]
done
