### ISSUE TITLE
[Feature Request] Support batching upsert in SQL Server Memory DB

### ISSUE THREAD

**Issue by marcominerva** [microsoft/kernel-memory#485]
### Context / Scenario

Kernel Memory now supports batching upsert in Memory DBs (see https://github.com/microsoft/kernel-memory/pull/441).

### The problem

Batching upsert can greatly improve the overall performance.

### Proposed solution

It would be great to have batching upsert support also in SQL Server Memory DB.

/cc @kbeaugrand 

### Importance

would be great to have

**Comment by dluc** [comment]
completed
