### ISSUE TITLE
.Net: Postgres connector support for vector database

### ISSUE THREAD

**Issue by thegovind** [microsoft/kernel-memory#50]

**Comment by thegovind** [comment]
Appreciate prioritizing this. Getting customer asks for pg connector.

**Comment by vanandrao** [comment]
Waiting for PGVector implementation

**Comment by basyonic** [comment]
It would be good to know if it is planned in roadmap anytime soon :)

**Comment by dluc** [comment]
@basyonic @vanandrao @thegovind Postgres integrated, with some nice new feature compared to other adapters: the table schema can be customized. Code and docs here: https://github.com/microsoft/kernel-memory/tree/main/extensions/Postgres
