### ISSUE TITLE
[Bug] MemoryWebClient - Rewind stream before posting to server

### ISSUE THREAD

**Issue by westdavidr** [microsoft/kernel-memory#508]
### Context / Scenario

I am using the Kernel Memory project's MemoryWebClient to upload a stream to the server. The stream needs to be rewound before it is posted, but currently, this step seems to be missing, causing the server to receive an empty stream.

### What happened?

When attempting to upload a stream using MemoryWebClient, the server receives an empty stream. It appears that the stream is not being rewound to its beginning before the upload, which results in the server not receiving the complete data as intended.

### Importance

a fix would make my life easier

### Platform, Language, Versions

Windows, C#, 0.51.240513.2

**Comment by dluc** [comment]
thank you!
