### ISSUE TITLE
[Bug] Wrong wording on the Cosine Similarity doc page

### ISSUE THREAD

**Issue by aguzev** [microsoft/kernel-memory#651]
### Context / Scenario

Read the document [Cosine Similarity](https://microsoft.github.io/kernel-memory/concepts/cosine-similarity). 

### What happened?

The document [Cosine Similarity](https://microsoft.github.io/kernel-memory/concepts/cosine-similarity) contains the following text:

> Cosine similarity is particularly useful when working with high-dimensional data such as word embeddings because it takes into account both the magnitude and direction of each vector. This makes it more robust than other measures like [Euclidean distance](https://github.com/microsoft/kernel-memory/blob/main/docs/concepts/euclidean-distance), which only considers the magnitude.

The distances of both sentences from truth are huge enough to rewrite them.

### Importance

a fix would make my life easier

### Platform, Language, Versions

KM Version 0.62.

**Comment by dluc** [comment]
Any suggestion about how to improve the text?

**Comment by aguzev** [comment]
I'm not a good English writer. Sorry for wasting time on basic math.
1. The cosine similarity does not take the magnitude into account. Dot product divided by the product of magnitudes is the cosine of the angle between the two vectors.
2. Euclidean distance always considers the angle between vectors. Euclidean distance between vectors (2) and (1) is 1 while Euclidean distance between vectors (2) and (-1) is 3. Distance between two arbitrary radius vectors of a circle is not necessarily zero.
3. Cosine similarity is often preferred because it compensates for magnitudes.

**Comment by dluc** [comment]
The sentence about cosine similarity seems ok to me, there's only a typo in the Euclidean part at the end. This change should be sufficient:

> Cosine similarity is particularly useful when working with high-dimensional data such as word embeddings because it takes into account both the magnitude and direction of each vector. This makes it more robust than other measures like Euclidean distance, which only considers the ~magnitude~ direction.


Given two n-dimensional points A and B
* A is a point (A1, A2, ..., An)
* B is a point (B1, B2, ..., Bn)

Cosine similarity:

![image](https://github.com/microsoft/kernel-memory/assets/371009/b396780f-8985-4331-92ac-0771bba29a79)

Where:

* A dot B  is the dot product of the vectors A and B 
![image](https://github.com/microsoft/kernel-memory/assets/371009/9452e860-a5fb-41ab-8311-7db5eed5e62a)

* \|A\|  is the magnitude of vector A
* \|B\|  is the magnitude of vector B

so cosine similarity **does** take into account the magnitude, as mentioned.

Euclidean distance:

![image](https://github.com/microsoft/kernel-memory/assets/371009/8b22d372-bd95-40f7-ba02-d19bb46206fb)

so Euclidean distance considers only the direction, not the magnitude -- this is the part to fix.

**Comment by dluc** [comment]
Docs updated

**Comment by aguzev** [comment]
I'm sorry for wasting your time on basic math but it is important.

In a Euclidean space $A·B = |A||B| cosβ$
$\frac{A·B}{|A||B|} = \frac{|A||B| cosβ}{|A||B|} = cosβ$
In fact, $\frac{A·B}{|A||B|}=cosβ$ is a definition of angle **β** between vectors.

Given three vectors A=(0,3), B=(0,2), and C=(0,1), 
Magnitudes are
$|A| = 3, |B| = 2, |C| = 1$

Euclidean distances ρ are
$ρ(A,B) = |\sqrt{(0-0)²+(3-2)²}| = 1$
$ρ(B,C) = |\sqrt{(0-0)²+(2-1)²}| = 1$
$ρ(B,A) = |\sqrt{(0-0)²+(3-1)²}| = 2$

Cosine similarities σ are
$σ(A,B) = \frac{0×0+3×2}{3×2} = \frac{6}{6} = 1 = cos0$
$σ(B,C) = \frac{0×0+2×1}{2×1} = \frac{2}{2} = 1 = cos0$
$σ(A,C) = \frac{0×0+3×1}{3×1} = \frac{3}{3} = 1 = cos0$

A,B, and C have same direction and different magnitudes. Euclidean distances are different. Cosine similarities equal. Euclidean distance takes into account **both** direction and magnitude.

[Cosine similarity on Wikipedia](https://en.wikipedia.org/wiki/Cosine_similarity)
[Dot product on Wikipedia](https://en.wikipedia.org/wiki/Dot_product)
