### ISSUE TITLE
AnthropicConfiguration class breaks the config class naming convention

### ISSUE THREAD

**Issue by akordowski** [microsoft/kernel-memory#705]
### Context / Scenario

All extensions config classes follow the convention `NameConfig`. The `AnthropicConfiguration` class is the only one which breaks with the convention. For consistency the class should be renamed to `AnthropicConfig`.

If wished I could provide a PR for this.

### What happened?

nothing

### Importance

edge case

### Platform, Language, Versions

all

**Comment by dluc** [comment]
PR is welcome :-) thanks
