### ISSUE TITLE
[Bug] Azure Cosmos DB for MongoDB: Unrecognized pipeline stage name: $listSearchIndexes

### ISSUE THREAD

**Issue by aitrailblazer** [microsoft/kernel-memory#716]
### Context / Scenario

Configured with:
Azure Cosmos DB for MongoDB (vCore)

Quick Start:
Command line (bash, curl)
https://microsoft.github.io/kernel-memory/quickstart/bash
cd tools
./upload-file.sh -f README.md -i doc01 -s http://127.0.0.1:9001

### What happened?

Command aggregate failed: Unrecognized pipeline stage name: $listSearchIndexes.

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

macOS

### Relevant log output

```shell
./upload-file.sh -f README.md -i doc01 -s http://127.0.0.1:9001
+ eval curl -v -F ''\''file1=@"README.md"'\''' -F ''\''index=""'\''' -F ''\''documentId="doc01"'\''' -F ''\''tags=""'\''' http://127.0.0.1:9001/upload
++ curl -v -F 'file1=@"README.md"' -F 'index=""' -F 'documentId="doc01"' -F 'tags=""' http://127.0.0.1:9001/upload
*   Trying 127.0.0.1:9001...
* Connected to 127.0.0.1 (127.0.0.1) port 9001
> POST /upload HTTP/1.1
> Host: 127.0.0.1:9001
> User-Agent: curl/8.6.0
> Accept: */*
> Content-Length: 2785
> Content-Type: multipart/form-data; boundary=------------------------bcLfKkbydiGUxY0Bf5kl0Q
>
* We are completely uploaded and fine
< HTTP/1.1 503 Service Unavailable
< Content-Type: application/problem+json
< Date: Tue, 23 Jul 2024 05:56:49 GMT
< Server: Kestrel
< Transfer-Encoding: chunked
<
* Leftovers after chunking: 11 bytes
* Connection #0 to host 127.0.0.1 left intact
{"type":"https://tools.ietf.org/html/rfc9110#section-15.6.4","title":"Document upload failed","status":503,"detail":"Command aggregate failed: Unrecognized pipeline stage name: $listSearchIndexes.
```

**Comment by dluc** [comment]
Did you run the code using the extension under development here https://github.com/microsoft/kernel-memory/pull/329 or the `MongoDBAtlas` connector?

Note that **MongoDbAtlas** and **Azure Cosmos DB for MongoDB** are not the same product, and the `MongoDBAtlas` connector doesn't work with the Azure variant.

**Comment by aitrailblazer** [comment]
Everything related is not production ready. I switched to AI Search and it's working fine
