### ISSUE TITLE
[Bug] Blazor, Azure, ImportFile pdf not working

### ISSUE THREAD

**Issue by aitrailblazer** [microsoft/kernel-memory#730]
### Context / Scenario

Deployed kernel memory to Azure.

Using a Blazor App.

importing ti the browser with InputFile:
```
                      var filePath = file.LocalFile?.FullName;

                    using var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
                    using var memoryStream = new MemoryStream();
                    await fileStream.CopyToAsync(memoryStream);
```

```
public IKernelMemory GetMemoryClient()
        {
            string endpoint = _parametersAzureService.KernelMemoryServiceEndpoint;
            string? apiKey = _parametersAzureService.KernelMemoryServiceApiKey;
            return new MemoryWebClient(endpoint, apiKey: apiKey);
        }
        
                 var memory = _kernelService.GetMemoryClient();
```
   
I want to do the same in the example:

```
           Console.WriteLine("Uploading a PDF with a news about NASA and Orion");
            var docId = await _kernelService.ImportDocumentAsync(new Document("doc003")
                .AddFile("file5-NASA-news.pdf")
                .AddTag("user", "Taylor")
                .AddTag("collection", "meetings")
                .AddTag("collection", "NASA")
                .AddTag("collection", "space")
                .AddTag("type", "news"));
```
                
                

### What happened?

but the following doesn't process the pdf file:                
```
                var document = new Document(memoryKey, tagsCollection).AddStream(fileName1, memoryStream);
                DocumentUploadRequest uploadRequest = new(document, indexName, Microsoft.KernelMemory.Constants.PipelineWithSummary);
                CancellationToken cancellationToken = default;
                var docId = await memory.ImportDocumentAsync(uploadRequest, context, cancellationToken);
```

### Importance

edge case

### Platform, Language, Versions

Azure, Blazor

**Comment by dluc** [comment]
Sorry but from the description it's not clear what the issue is. Could you explain what happens? Why do you think the PDF is not processed?

**Comment by aitrailblazer** [comment]
I want to import file from a browser using Blazor app on Azure.

I made it work using the following:
                        using var memoryStream = new MemoryStream();
                        using Stream fileStream = File.OpenRead(filePath);
                        await fileStream.CopyToAsync(memoryStream);
                        memoryStream.Seek(0, SeekOrigin.Begin);

**Comment by dluc** [comment]
cool, great to hear the problem is solved :-)

**Comment by aitrailblazer** [comment]
I have now a new issue. Trying to upload bigger files trough the browser. At 100KB it gets really slow. Bigger than that doesn't works at all.
