### ISSUE TITLE
[Bug] the new bicep template for Azure is not working

### ISSUE THREAD

**Issue by aitrailblazer** [microsoft/kernel-memory#733]
### Context / Scenario

Using the new bicep template

### What happened?

Subscription '<my subscription>' is not registered with the required resource providers, please register with the resource providers Microsoft.App and Microsoft.ContainerService. (Code: SubscriptionIsNotRegistered)

additionally
gpt-4o-mini

cannot be deployed.

The model 'Format: OpenAI, Name: gpt-4o-mini, Version: ' of account deployment is not supported. (Code: DeploymentModelNotSupported

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

Azure, Blazor

**Comment by dluc** [comment]
@cherchyk FYI

**Comment by cherchyk** [comment]
Hi, @aitrailblazer,

Please follow steps here https://github.com/cherchyk/kernel-memory/tree/pages/infra to register providers.
This documentation is currently in PR so while it's on review you can access it from the URL I provided.

**Comment by cherchyk** [comment]
Regrading a second problem "The model 'Format: OpenAI, Name: gpt-4o-mini, Version: ' of account deployment is not supported. (Code: DeploymentModelNotSupported"

Please check if you can create an OpenAI service in the same region using Azure Portal and then create Deployment with model 'gpt-4o-mini'. Please use same Capacity you used for the Kernel Memory deployment.

**Comment by dluc** [comment]
Looks like the issue has been addressed, otherwise please feel free to report here, thanks!
