### ISSUE TITLE
[Bug] Cancellation is not performed

### ISSUE THREAD

**Issue by aropb** [microsoft/kernel-memory#737]
### Context / Scenario

Hi,

The cancellation of the request is not performed in SearchClient.GenerateAnswer(). 
This place does not provide a response to the cancellation of a long-term request (with used cancellationToken).

My code:
MemoryAnswer answer = await memory.AskAsync(question: question, filters: filters, cancellationToken: cancellationToken);

Thanks.

### What happened?

When canceling the execution of an http request, the response generation must stop!

### Importance

Critical

### Platform, Language, Versions

Windows 11, NET 8.0.7, KM 0.70.240803.1

**Comment by dluc** [comment]
@aropb SearchClient.GenerateAnswer() passes the cancellation token to the text generator, so this could be a problem with a specific generator. Which text generator are you using?

**Comment by aropb** [comment]
I do not know for sure :) LLamaSharp?

**Comment by dluc** [comment]
KM LLamaSharp text generator passes the cancellation token, then it's up to the LLamaSharp library to handle the cancellation internally:

https://github.com/microsoft/kernel-memory/blob/84653a2208a50d20ea3c7db81d3d8922bc19750d/extensions/LlamaSharp/LlamaSharp/LlamaSharpTextGenerator.cs#L128-L130

You might want to raise a bug in LLamaSharp repo for this one
