### ISSUE TITLE
AzureAISearchConfig does not have a way to specify index name

### ISSUE THREAD

**Issue by bancroftway** [microsoft/kernel-memory#742]
### Context / Scenario

The AzureAISearchConfig class does not have an Index property. When ingesting documents, Kernel Memory creates an index named "default".  However, when using the KM plugin from Semantic Kernel, there is an option to specify 'defaultIndex'. Therefore, the AzureAISearchConfig  should be modified to add an Index property, and when ingesting documents, the created index should should use this name.

Example AzureAISearchConfig usage:
```
var azureAISearchConfig = new AzureAISearchConfig()
{
    Auth = AzureAISearchConfig.AuthTypes.APIKey,
    APIKey = "xxx"!,
    Endpoint = "yyy"!,               
    UseHybridSearch = true,
};
```

Screenshot showing index created by Kernel Memory
![image](https://github.com/user-attachments/assets/e71eefde-919d-4c19-85a7-08cd67fb8281)

Example code showing KM memory plugin and setting the "defaultIndex" property.
```
var memoryPlugin = skKernel.ImportPluginFromObject(
    new MemoryPlugin(kmKernel, 
    defaultIndex: "zzz"!, 
    waitForIngestionToComplete: true),
    pluginName);
```

### What happened?

AzureAISearchConfig  should provide a way to specify Index name

### Importance

a fix would make my life easier

### Platform, Language, Versions

.Net 8, C#, ASP.Net Core Blazor, KM 0.70.240803.1

**Comment by dluc** [comment]
The configuration is not specific to the storage type (e.g. Azure AI Search), but to the service. 

See `DefaultIndexName`

https://github.com/microsoft/kernel-memory/blob/9b63662ed706e42ca4eb7c137ca0de60460e163e/service/Core/Configuration/KernelMemoryConfig.cs#L163

https://github.com/microsoft/kernel-memory/blob/9b63662ed706e42ca4eb7c137ca0de60460e163e/service/Service/appsettings.json#L113C6-L113C22
