### ISSUE TITLE
[Bug] 'Object reference not set to an instance of an object.' awaiting ImportTextAsync() 

### ISSUE THREAD

**Issue by javierbp00** [microsoft/kernel-memory#763]
### Context / Scenario

I am using Kernel Memory to add a text and use it to answer a question. Everything seems to work fine but when the code gets in the line of await ImportTextAsync(), an exeception of Object reference not set to an instance of an object is risen.

### What happened?

Using the following packages:

PackageReference Include="Microsoft.KernelMemory.Core" Version="0.71.240820.1" />
PackageReference Include="Microsoft.KernelMemory.SemanticKernelPlugin" Version="0.71.240820.1" />
PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.17.1" />
PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.17.1" />
PackageReference Include="Microsoft.SemanticKernel.Plugins.Memory" Version="1.17.1-alpha" />

I created a Kernel Memory Builder and specified the ChatCompletion and the TextEmbedding. I am using Ollama running locally with two models previously pulled as shown:

```csharp
KernelCore.kernelMemory = new KernelMemoryBuilder()
    .WithOpenAITextEmbeddingGeneration(new OpenAIConfig()
    {
        APIKey = "ollama",
        Endpoint = "http://localhost:11434/api",
        EmbeddingModel = "mxbai-embed-large",
        EmbeddingDimensions = 3
    }
    )
    .WithOpenAITextGeneration(new OpenAIConfig()
    {
        APIKey = "ollama",
        Endpoint = "http://localhost:11434",
        TextModel = "llama3.1"
    })
    .Build<MemoryServerless>();

await KernelCore.kernelMemory.ImportTextAsync("My text goes here.");
```

However, when the debugger gets to de awaiting line, the exception is risen. Debugging, I found that the exception comes from the file [ClientCore.cs](https://github.com/microsoft/semantic-kernel/blob/78289af2851a10b9f857051cb22bb00c7528f555/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs), in line 305.

In the method GetEmbeddingsAsync(), when creating an instance of EmbeddingOptions,

```csharp
var embeddingsOptions = new EmbeddingsOptions(this.DeploymentOrModelName, data)
            {
                Dimensions = dimensions
            };
```
all the fields are filled, but the instance returns a null value, so when trying to do 

```csharp
var response = await RunRequestAsync(() => this.Client.GetEmbeddingsAsync(embeddingsOptions, cancellationToken)).ConfigureAwait(false);
```

This rise the exception.

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

C#

PackageReference Include="Microsoft.KernelMemory.Core" Version="0.71.240820.1" />
PackageReference Include="Microsoft.KernelMemory.SemanticKernelPlugin" Version="0.71.240820.1" />
PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.17.1" />
PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.17.1" />
PackageReference Include="Microsoft.SemanticKernel.Plugins.Memory" Version="1.17.1-alpha" />

**Comment by dluc** [comment]
Update: KM v0.72 now includes an Ollama connector, making it extremely easier to work with local models

Example here: https://github.com/microsoft/kernel-memory/blob/main/examples/212-dotnet-ollama/Program.cs

**Comment by dluc** [comment]
The issue was caused by Ollama not being fully supported by the underlying SK + Azure AI SDK. 

The recommendation is to **not use** `WithOpenAITextEmbeddingGeneration`/`WithOpenAITextGeneration` and use `WithOllamaTextGeneration` and `WithOllamaTextEmbeddingGeneration` instead.
