### ISSUE TITLE
[Bug] When switching to new versions of KM and LLamaSharp, there was a slowdown

### ISSUE THREAD

**Issue by aropb** [microsoft/kernel-memory#765]
### Context / Scenario

After upgrading from KM 0.61 and LLamaSharp 0.13 to the latest versions, the processing ImportDocumentAsync/AskAsync speed has significantly decreased, almost 2 times.
All settings and equipment are the same. I see that the GPU is now less loaded, previously CUDA was loaded more than 80%.

Import:
![Screenshot_1](https://github.com/user-attachments/assets/d069ca43-b104-4850-8020-cfa7826efbf0)

Ask:
![image](https://github.com/user-attachments/assets/7bb512f2-9695-46ee-87b3-64a77f9eec1a)

How do I get back to my previous speed?
Thanks.

### What happened?

GPU load is more than 80%

### Importance

edge case

### Platform, Language, Versions

Operating system: Windows 11
.NET runtime version: 8.0.8
LLamaSharp version: 0.16.0
KernelMemory: 0.71...
CUDA version (if you are using cuda backend): 12
CPU & GPU device: CPU or GPU, Intel Core Ultra 9 & RTX 3090

**Comment by dluc** [comment]
hi @aropb you should try loading LLamaSharp backend explicitly, see https://github.com/microsoft/kernel-memory/blob/main/service/Service/Service.csproj

unfortunately llamasharp doesn't allow to load all the backends and choose one at runtime, so you need to compile the code manually, after adding CUDA (in your case).

you could also opt for ollama, which I believe doesn't suffer from this limitation

**Comment by aropb** [comment]
Everything was done correctly and the backend was installed, of course, because it worked on version 0.13.0 and is working now, but slower!

**Comment by aropb** [comment]
Unfortunately, I don't understand how I can use something other than LlamaSharp with KM.

**Comment by dluc** [comment]
nevermind, I spent some time today testing the feasibility of ollama, and unfortunately the underlying OpenAI connector doesn't work with it. Ollama provides an openai compatible endpoint, but the connector we're using in SK/KM doesn't work 100% with, throwing exceptions. About ollama, someone will need to add a new connector, if needed.

About llamasharp perf, I can only suggest reaching out to that project team.

**Comment by dluc** [comment]
Update: KM v0.72 now includes an Ollama connector, making it extremely easier to work with local models

**Comment by dluc** [comment]
@aropb there's a new version out with new LLamasharp libs version, in case you want to give it a test

**Comment by aropb** [comment]
This problem is LLamaSharp
