### ISSUE TITLE
Deleting documents requires knowing document IDs

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/kernel-memory#80]
Currently, deleting documents or memories requires knowing the document IDs. A lot of times, Apps don't track the document IDs. Instead, they may track something that is more relevant to the apps. For example, a chat app may track documents or memories by chat session IDs, which can be a tag in the Semantic Memory land.

Unfortunately, results returned by the `search/` and `ask/` endpoints do not contain the document IDs. For apps to delete documents or memories, these endpoints need to return the document IDs.

Proposed fix: add the document ID as a property in the `Citation` object.

**Comment by dluc** [comment]
Fixed
