### ISSUE TITLE
[Bug] Error uploading .docx file. Getting error "File contains corrupted data"

### ISSUE THREAD

**Issue by bancroftway** [microsoft/kernel-memory#802]
### Context / Scenario

I am trying to ingest a .docx file which I can open and read with no issues. KM is throwing an exception "File contains corrupted data". Please see below screenshot

### What happened?

![image](https://github.com/user-attachments/assets/acf0eb8f-986f-4d1b-8206-f7a887c5dbdd)

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

.Net 9

### Relevant log output

```shell
"File contains corrupted data"
```

**Comment by dluc** [comment]
Is the file protected by DRM? It could be opening for you because your local environment has the necessary credentials.
Try using a different reader, such as OpenOffice, to see if it works.

Kernel Memory file extraction depends on the OpenXML format. Word might handle certain errors that OpenXML libraries strictly enforce.

If you’re able to share the file, I can take a look. Otherwise, there might not be much else we can do.

**Comment by marcominerva** [comment]
Also, are you using at least Kernel Memory [v0.74.240919.1](https://github.com/microsoft/kernel-memory/releases/tag/packages-0.74.240919.1)? Previous versions used **DocumentFormat.OpenXml v2.20.0**, while the last ones relies on version **3.10**, that have solved some issues related to corrupted (or potentially corrupted) files.

**Comment by qmatteoq** [comment]
I started to get the same issue with some files and it turned out it was the labelling. The files were previously copied on my work OneDrive, which enforces a Confidential label. Copying the file outside of OneDrive and changing the label to "Non Business" solved the problem for me.

**Comment by marcominerva** [comment]
Verify also the value of your `docContent` byte arrray, as I suggested here: https://github.com/microsoft/kernel-memory/issues/803#issuecomment-2376165901 (it may be a related issue).

**Comment by dluc** [comment]
> I started to get the same issue with some files and it turned out it was the labelling. The files were previously copied on my work OneDrive, which enforces a Confidential label. Copying the file outside of OneDrive and changing the label to "Non Business" solved the problem for me.

I stumbled on this one too, hopefully there's a way to remove these labels programmatically, before the ingestion process.

**Comment by dluc** [comment]
Closing for now until we get more information. This is likely an issue with file credentials/confidentiality.
