### ISSUE TITLE
[Bug] Token Output Is Significantly Less Than Configured MaxTokenTotal in Azure OpenAI SDK

### ISSUE THREAD

**Issue by thammermann** [microsoft/kernel-memory#830]
### Context / Scenario

Description:

I'm experiencing an issue with the Azure OpenAI SDK where the token output is significantly less than what I've configured in MaxTokenTotal. Despite setting MaxTokenTotal to 4086, the generated responses are consistently cut off at around 300-400 tokens. This results in incomplete answers from the model.

Steps to Reproduce:

Configure AzureOpenAIConfig for both text generation and embedding generation with MaxTokenTotal set to 4086.
Build the memory using KernelMemoryBuilder with the text generation and embedding configurations.
Import a document using memory.ImportDocumentAsync(filePath: path);.
Create a prompt and query the model using var answer = await memory.AskAsync(prompt);.
Observe that the model's output is cut off and does not utilize the full token limit specified.
Code Snippet:

csharp
Code kopieren
var azureConfig = new AzureOpenAIConfig()
{
    APIKey = "YOUR_API_KEY",
    Deployment = "gpt-4o-mini",
    Endpoint = "MyEndPoint",
    Auth = AzureOpenAIConfig.AuthTypes.APIKey,
    APIType = AzureOpenAIConfig.APITypes.ChatCompletion,
    MaxTokenTotal = 4086
};

var config = new AzureOpenAIConfig()
{
    Auth = AzureOpenAIConfig.AuthTypes.APIKey,
    APIType = AzureOpenAIConfig.APITypes.EmbeddingGeneration,
    Deployment = "text-embedding-3-large",
    // EmbeddingModel = "text-embedding-3-large",
    APIKey = "YOUR_API_KEY",
    Endpoint = "MyEndpoint",
    MaxTokenTotal = 4086
};

var memory = new KernelMemoryBuilder()
    .WithAzureOpenAITextGeneration(azureConfig)
    .WithAzureOpenAITextEmbeddingGeneration(config)
    .WithAzureAISearchMemoryDb("MyEndpoint", "YOUR_SEARCH_API_KEY")
    .Build<MemoryServerless>();

await memory.ImportDocumentAsync(filePath: path);
string prompt = PromptTemplate.EuRechte();
var answer = await memory.AskAsync(prompt);
Console.WriteLine(answer.Result);

foreach (var source in answer.RelevantSources)
{
    Console.WriteLine($"{source.SourceName} - {source.Link} [{source.Partitions.First().LastUpdate} / {source.Partitions.First().Relevance}]");
}

### What happened?

Expected Behavior:

The model should generate responses that utilize the full MaxTokenTotal limit set in the configuration (up to 4086 tokens), providing complete answers without being cut off.

Actual Behavior:

The responses are consistently cut off at around 300-400 tokens, well below the configured MaxTokenTotal. This leads to incomplete outputs from the model.

Additional Information:

The issue occurs regardless of the prompt used.
Adjusting the MaxTokenTotal value does not seem to affect the actual length of the token output.
No errors or exceptions are thrown during execution.
Environment:

### Importance

edge case

### Platform, Language, Versions

Microsoft.KernelMemory.Core: 0.78.241007.1
Microsoft.KernelMemory.AI.AzureOpenAI: 0.78.241007.1
Programming Language: C#
.NET Version: 8
Operating System: Windows 11
Solution Type: Console App

**Comment by marcominerva** [comment]
`MaxTokenTotal` is the max number of tokens supported by the model (for example, for `gpt-4o-mini` is 128K and for `text-embedding-3-large` is 8191). If you want to define how many tokens are available for the response text, you need to set the `AnswerTokens` property using `WithSearchClientConfig`:

```csharp
.WithSearchClientConfig(new()
{
    EmptyAnswer = "No results found. Please try again.",
    AnswerTokens = 800,   // Default is 300
    MaxMatchesCount = 10
})
```

**Comment by thammermann** [comment]
thanks :)

**Comment by dluc** [comment]
Assuming the problem has been addressed :-)
