### ISSUE TITLE
[Bug] Docker image fails to start when ASPNETCORE_ENVIRONMENT set to Production

### ISSUE THREAD

**Issue by alexmg** [microsoft/kernel-memory#851]
### Context / Scenario

Starting from tag `0.80.241017.2` the service cannot be started in a Docker container when the `ASPNETCORE_ENVIRONMENT` environment variable is to anything other than `Development`.

### What happened?

The exception below is thrown as soon as the service starts.

```
Unhandled exception. System.ApplicationException: Sensitive data logging can be enabled only in a development environment. Check ASPNETCORE_ENVIRONMENT env var.
   at Microsoft.KernelMemory.Diagnostics.SensitiveDataLogger.set_Enabled(Boolean value) in /src/service/Abstractions/Diagnostics/SensitiveDataLogger.cs:line 25
   at Microsoft.KernelMemory.Service.Program.Main(String[] args) in /src/service/Service/Program.cs:line 52
```

This is a result of a recent change to disable sensitive logging as the very first line of code during startup.

```csharp
SensitiveDataLogger.Enabled = false;
```

The `SensitiveDataLogger` will throw an exception when the property setter is called unless the environment `Development`. This occurs regardless of the value the property is being set to. Because the container image runs using the `Production` environment (as it should) the exception is thrown, and the service fails to start.

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

Docker image: `kernelmemory/service:0.80.241017.2`

**Comment by dluc** [comment]
This should fix it https://github.com/microsoft/kernel-memory/pull/852

**Comment by alexmg** [comment]
Thanks @dluc. I started a PR and have some unit tests if you're interested in adding those.

**Comment by dluc** [comment]
Unit tests welcome :-) Release with the fix in progress

**Comment by dluc** [comment]
I'd skip the `[InlineData("Staging")]` and `[InlineData("Production")]` tags

**Comment by alexmg** [comment]
I will open a PR with the additional unit tests.

**Comment by dluc** [comment]
Should be fixed in 0.90.241021.1, could you confirm?

Thanks!!

**Comment by alexmg** [comment]
I can confirm this is now fixed. 👍

Thank you for the quick turnaround on the fix @dluc!

**Comment by marcominerva** [comment]
@dluc I'm wondering if we could support also the **DOTNET_ENVIRONMENT** variable (to correctly support all kind of applications): https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments.

**Comment by dluc** [comment]
> [@dluc](https://github.com/dluc) I'm wondering if we could support also the **DOTNET_ENVIRONMENT** variable (to correctly support all kind of applications): https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments.

so many env vars :-D I'm afraid about the need to handle all the permutations in code, documentation, case sensitivity etc.

Considering that we're running a web service, do we need both env vars? I'm not aware of scenarios where a user would expect DOTNET_ENVIRONMENT to affect the solution.

**Comment by marcominerva** [comment]
We must consider also serverless scenarios, for example I may use Kernel Memory in serverless mode inside a Windows Service or Linux daemon, so I call the `Host.CreateBuilder` method, that searches for **DOTNET_** environment variables: https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.host.createdefaultbuilder?view=net-8.0#microsoft-extensions-hosting-host-createdefaultbuilder

**Comment by dluc** [comment]
We could support DOTNET_ENVIRONMENT in the logger classes, that's the only code relying on the environment type.

However, I don't think there's need to set the env var in the docker file or support it in Service's code.

**Comment by marcominerva** [comment]
Yes, I agree that we need the support for DOTNET_ENVIRONMENT in the logger.
