### ISSUE TITLE
[Bug] ElasticSearch Index naming

### ISSUE THREAD

**Issue by yfbenkhalifa** [microsoft/kernel-memory#864]
### Context / Scenario

When indexing a document using KernelMemory and ElasticSearch with the following configuration: 
`"ElasticsearchConfig": {
        "Endpoint": "<...>",
        "CertificateFingerPrint": "<...>",
        "Username": "<...>",
        "Password": "<...>",
        "IndexPrefix":  "testnode"
      },`

### What happened?

The created index would happen to have the word "default" at the end of the node name
![Image](https://github.com/user-attachments/assets/ab6909c9-c4bb-488c-831a-40c22501b18f)

### Importance

a fix would make my life easier

### Platform, Language, Versions

.NET 8

**Comment by marcominerva** [comment]
As the property name implies, `IndexPrefix` is just the prefix for the index, not the whole name. The actual index name is `IndexPrefix `+ `IndexName `.  If you want to change the index name at all, leave the `IndexPrefix` property of `ElasticsearchConfig` empty and set `DefaultIndexName` in the `KernelMemoryConfig`:

```csharp
.With(new KernelMemoryConfig()
{
    DefaultIndexName = "testnode"
})
```

**Comment by yfbenkhalifa** [comment]
Oh alright, I did not notice that configuration for the KernelMemory. Thank you!
