### ISSUE TITLE
Support SQL Server as a memory source

### ISSUE THREAD

**Issue by ADefWebserver** [microsoft/kernel-memory#90]
SQL Server works fine as a memory source to store vector embeddings. It is the most cost effective method. See: [Azure OpenAI RAG Pattern using a SQL Vector Database](https://blazorhelpwebsite.com/ViewBlogPost/10067)

**Comment by marcominerva** [comment]
You can use it with this third-party extension: https://github.com/kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer. You can find an example of its integration in my GitHub repository at https://github.com/marcominerva/OpenAIEmbeddingSample.

**Comment by dluc** [comment]
MS SQL server connector is now available in the repo, thanks to @kbeaugrand
