### ISSUE TITLE
Remove ACS limit increase when filtering

### ISSUE THREAD

**Issue by anthonypuppo** [microsoft/kernel-memory#92]
Depends on #86.

The latest preview API version `2023-10-01-Preview` adds a new parameter `vectorFilterMode` for specifying prefiltering (default) or postfiltering in the query. Updating the search options to use postfiltering (I think?) will remove the need for the below.

https://github.com/microsoft/semantic-memory/blob/d041156f28a5ef3e141e9ba2e7bbf0b7b6c1e394/dotnet/CoreLib/MemoryStorage/AzureCognitiveSearch/AzureCognitiveSearchMemory.cs#L129

**Comment by dluc** [comment]
We'll need to test and verify the behavior with/without. There seems to be multiple permutations of these settings that we need to consider. Currently we own the schema so it's simpler, but we're planning to support indexes created outside, in which case we don't know the configuration. I would hold on, assuming that the current code is not breaking the results, at worst affecting the perf, something we can accept for a while until we have all the information.
