### ISSUE TITLE
[Bug] AzureIdentity Default cannot get Token for Azure Government Cloud

### ISSUE THREAD

**Issue by coryisakson** [microsoft/kernel-memory#943]
### Context / Scenario

Deploying a solution to Azure Gov Cloud that is configured with AzureIdentity for Azure OpenAI, Search, and Blobs. 

### What happened?

When using the memory.SearchAsync endpoint we are unable to get a Token for the AzureOpenAI. The code attempts to connect to Azure OpenAI with a scope for the public cloud.
Scopes: [ https://cognitiveservices.azure.com/.default ]

### Importance

a fix would make my life easier

### Platform, Language, Versions

App Service on Linux .NET 8
Kernel Memory 0.94.241201.1

### Relevant log output

```shell

```

**Comment by dluc** [comment]
Possible fix: https://github.com/microsoft/kernel-memory/pull/944

**Comment by dluc** [comment]
Version **0.95.241216.2** includes updates to address this across multiple services:

* Azure AI Search
* Azure AI Document Intelligence
* Azure OpenAI
* Azure Blobs
* Azure Queues

See the new `AzureIdentityAudience` config value for these services. The value and its format vary depending on the service.

**Comment by dluc** [comment]
Fixed in 0.95.241216.2
