### ISSUE TITLE
Consistently handle index not found error in all memory storage solutions

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/kernel-memory#95]
Currently, when searching in an index that doesn't exist, Azure Cognitive Search and Simple Storage will return an empty list, while qDrant will throw an exception. This makes it difficult for clients to handle errors consistently. Introduce a new exception `IndexNotFoundException` that all memory solutions should throw when search in an index that does not exist.

**Comment by geffzhang** [comment]
Is there a plan when this issue will be fixed, I'm using Qdrant and am stumped by this issue, qdrant doesn't work on chat-copilot  https://github.com/microsoft/chat-copilot/issues/547

**Comment by dluc** [comment]
Further improvements applied to Azure AI Search, Postgres and Qdrant connectors. /cc @geffzhang
